const punePhotographers100 = [
  {
    "id": 500,
    "name": "Pune Dusk Photography",
    "founder": "Abhay Lohokare",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@punedusk",
    "websiteStatus": "Has website (punedusk.com) — NO booking form",
    "phone": "—",
    "email": "info@punedusk.com",
    "notes": "Founded by Abhay Lohokare (Vancouver Film School). Candid wedding & cinematic films. No online booking.",
    "url": "https://demo.claraverse.in/pune-dusk-photography",
    "pitch": "Hey Abhay, I'm truly impressed by the candid and cinematic storytelling in Pune Dusk Photography's wedding portfolio. I noticed your website currently doesn't feature an online booking system, which often means managing inquiries manually. To show you how seamless this could be, we've crafted a personalized showcase demo just for Pune Dusk Photography: https://demo.claraverse.in/pune-dusk-photography. Would love to get your feedback on this.",
    "slug": "pune-dusk-photography"
  },
  {
    "id": 501,
    "name": "Ajinkya Jadhav Photography",
    "founder": "Ajinkya Jadhav",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@ajinkya_jadhav_photography",
    "websiteStatus": "Has website (ajinkyajadhav.co.in) — NO booking form",
    "phone": "—",
    "email": "info@ajinkyajadhav.co.in",
    "notes": "Artistic portraits & storytelling wedding coverage. No booking system.",
    "url": "https://demo.claraverse.in/ajinkya-jadhav-photography",
    "pitch": "Hey Ajinkya, I'm truly impressed by your artistic portraits and storytelling approach to wedding photography; your work beautifully captures those special moments. I noticed your website, ajinkyajadhav.co.in, doesn't feature an online booking system, which likely means you're handling all inquiries and bookings manually. We've actually put together a personalized demo for you at https://demo.claraverse.in/ajinkya-jadhav-photography to show how seamless this could be. Would love to get your feedback on this.",
    "slug": "ajinkya-jadhav-photography"
  },
  {
    "id": 502,
    "name": "Rachna & Niranjan Photography",
    "founder": "Rachna & Niranjan",
    "city": "Pune",
    "category": "Wedding/Pre-Wedding",
    "instagram": "@rachnaniranjan_photography",
    "websiteStatus": "Has website (rachnaniranjan.com) — NO booking form",
    "phone": "+91-8983524055",
    "email": "info@rachnaniranjan.com",
    "notes": "Husband-wife duo. Documentary style. Destination weddings. Phone + email verified.",
    "url": "https://demo.claraverse.in/rachna-niranjan-photography",
    "pitch": "Hey Rachna & Niranjan, Your documentary style photography beautifully captures the authentic emotions of each moment, especially in your destination weddings. I noticed your website, rachnaniranjan.com, doesn't currently offer an online booking system, which often means managing inquiries and bookings manually. We've actually built a personalized showcase demo specifically for Rachna & Niranjan Photography to illustrate how seamless this could be: https://demo.claraverse.in/rachna-niranjan-photography. Would love to get your feedback on this.",
    "slug": "rachna-niranjan-photography"
  },
  {
    "id": 503,
    "name": "KnotsbyAMP",
    "founder": "Anupam and Soumi",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@knotsbyamp",
    "websiteStatus": "Has website (knotsbyamp.com) — NO booking form",
    "phone": "—",
    "email": "info@knotsbyamp.com",
    "notes": "BITS Pilani & ILS Law alumni. Storytelling approach. Ritz Carlton Pune featured.",
    "url": "https://demo.claraverse.in/knotsbyamp",
    "pitch": "Hey Anupam and Soumi, Your storytelling approach to wedding photography, beautifully capturing genuine emotions, truly stands out. I noticed your website, knotsbyamp.com, doesn't currently feature an online booking system, which often means manual handling of inquiries. We've actually built a personalized showcase demo for KnotsbyAMP at https://demo.claraverse.in/knotsbyamp to illustrate how seamless this could be. Would love to get your feedback on this.",
    "slug": "knotsbyamp"
  },
  {
    "id": 504,
    "name": "MH12 Weddings",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Pre-Wedding",
    "instagram": "@mh12weddings",
    "websiteStatus": "Has website (mh12weddings.com) — NO booking form",
    "phone": "—",
    "email": "contact@mh12weddings.com",
    "notes": "Vibrant & creative wedding photography. Candid + cinematic films. No booking.",
    "url": "https://demo.claraverse.in/mh12-weddings",
    "pitch": "Hey Team, Your vibrant and creative wedding photography, especially the candid and cinematic style, truly stands out. I noticed your beautiful website, mh12weddings.com, doesn't currently offer an online booking system, which often means handling inquiries manually. We've actually put together a personalized showcase demo for MH12 Weddings to illustrate how seamless online booking could be: https://demo.claraverse.in/mh12-weddings. Would love to get your feedback on this.",
    "slug": "mh12-weddings"
  },
  {
    "id": 505,
    "name": "Amour Affairs Photography",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@amouraffairs",
    "websiteStatus": "Has website (amouraffairs.in) — NO booking form",
    "phone": "—",
    "email": "hello@amouraffairs.in",
    "notes": "Romantic storytelling & elegant wedding visuals. No online booking.",
    "url": "https://demo.claraverse.in/amour-affairs-photography",
    "pitch": "Hey Team, Your romantic storytelling and elegant wedding visuals truly capture the essence of each couple's special day. I noticed your beautiful website, amouraffairs.in, currently handles bookings manually without an online system. We've actually built a personalized showcase demo for Amour Affairs Photography to illustrate how seamless online booking could be: https://demo.claraverse.in/amour-affairs-photography Would love to get your feedback on this.",
    "slug": "amour-affairs-photography"
  },
  {
    "id": 506,
    "name": "The Picture Talk Photography",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@thepicturetalk",
    "websiteStatus": "Has website (thepicturetalk.myportfolio.com) — NO booking form",
    "phone": "—",
    "email": "info@thepicturetalk.com",
    "notes": "Documentary style. Natural candid moments. myportfolio subdomain.",
    "url": "https://demo.claraverse.in/the-picture-talk-photography",
    "pitch": "Hey Team, I was really impressed by the natural, candid moments you capture in your documentary-style wedding photography. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've built a personalized showcase demo specifically for The Picture Talk Photography to show how this could streamline your process: https://demo.claraverse.in/the-picture-talk-photography. Would love to get your feedback on this.",
    "slug": "the-picture-talk-photography"
  },
  {
    "id": 507,
    "name": "Frozen Memories",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@frozenmemories.in",
    "websiteStatus": "Has website (frozenmemories.in) — NO booking form",
    "phone": "—",
    "email": "contact@frozenmemories.in",
    "notes": "Cinematic wedding storytelling. Emotional & creative visuals. No booking.",
    "url": "https://demo.claraverse.in/frozen-memories",
    "pitch": "Hey Team, Your cinematic wedding storytelling and emotional visuals at Frozen Memories truly stand out. I noticed your website, frozenmemories.in, doesn't have an online booking system, which likely means you're handling all inquiries manually. We've actually put together a personalized demo for Frozen Memories to show how seamless this could be: https://demo.claraverse.in/frozen-memories Would love to get your feedback on this.",
    "slug": "frozen-memories"
  },
  {
    "id": 508,
    "name": "Bliss Memoir Photography & Films",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@blissmemoir",
    "websiteStatus": "Has website (blissmemoir.com) — NO booking form",
    "phone": "—",
    "email": "info@blissmemoir.com",
    "notes": "Warm & emotional wedding photography. Candid + artistic portraits. No booking.",
    "url": "https://demo.claraverse.in/bliss-memoir-photography-films",
    "pitch": "Hey Team, Your portfolio at Bliss Memoir Photography & Films truly captures the warm, emotional essence of weddings with a beautiful blend of candid and artistic portraits. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've actually built a personalized showcase demo specifically for you to illustrate how seamlessly this could integrate: https://demo.claraverse.in/bliss-memoir-photography-films. Would love to get your feedback on this.",
    "slug": "bliss-memoir-photography-films"
  },
  {
    "id": 509,
    "name": "Capture The Image Films",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Cinematography",
    "instagram": "@capture_the_image_films",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "info@capturetheimagefilms.com",
    "notes": "Cinematic wedding storytelling. Instagram-only presence. No booking.",
    "url": "https://demo.claraverse.in/capture-the-image-films",
    "pitch": "Hey Team, Your cinematic wedding storytelling on Instagram is truly captivating. I noticed you don't have a website, which means managing bookings and showcasing your incredible work might be more challenging than it needs to be. We've actually built a personalized showcase demo specifically for Capture The Image Films to illustrate how seamless this could be: https://demo.claraverse.in/capture-the-image-films Would love to get your feedback on this.",
    "slug": "capture-the-image-films"
  },
  {
    "id": 510,
    "name": "The Bridal Photography",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Pre-Wedding",
    "instagram": "@thebridalphotography",
    "websiteStatus": "Has website (thebridal.photography) — NO booking form",
    "phone": "+91-8390367637",
    "email": "—",
    "notes": "Award-winning wedding & maternity. 4.9★ 1179 reviews. Packages from ₹6000. Phone verified.",
    "url": "https://demo.claraverse.in/the-bridal-photography",
    "pitch": "Hey Team, your award-winning candid and heartfelt approach to wedding and maternity photography truly stands out. I noticed your website lacks an online booking system, meaning bookings are handled manually. We even built a personalized showcase demo specifically for you to show how this works: https://demo.claraverse.in/the-bridal-photography. Would love to get your feedback on this.",
    "slug": "the-bridal-photography"
  },
  {
    "id": 511,
    "name": "Pixelworks Photography",
    "founder": "Team",
    "city": "Pune (Balewadi)",
    "category": "Wedding/Pre-Wedding",
    "instagram": "@pixelworks.in",
    "websiteStatus": "Has website (pixelworks.in) — NO booking form",
    "phone": "+91-9284880394",
    "email": "—",
    "notes": "8+ years. 100+ weddings. Balewadi studio. Phone verified. WhatsApp available.",
    "url": "https://demo.claraverse.in/pixelworks-photography",
    "pitch": "Hey Team, Your extensive experience in wedding and pre-wedding photography truly shines through, capturing such beautiful and candid moments for couples. I noticed your website, pixelworks.in, doesn't currently offer an online booking system, which often means managing inquiries and bookings manually. We've actually built a personalized showcase demo specifically for Pixelworks Photography to illustrate how seamless online booking could be: https://demo.claraverse.in/pixelworks-photography. Would love to get your feedback on this.",
    "slug": "pixelworks-photography"
  },
  {
    "id": 512,
    "name": "Aniket Kanade Photography",
    "founder": "Aniket Kanade",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@aniketkanade",
    "websiteStatus": "Has website (aniketkanadephotography.com) — NO booking form",
    "phone": "—",
    "email": "—",
    "notes": "Best Wedding Photographer in Pune. Candid & pre-wedding specialist. No booking.",
    "url": "https://demo.claraverse.in/aniket-kanade-photography",
    "pitch": "Hey Aniket, I'm truly impressed by your candid and pre-wedding photography, capturing such genuine moments. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've built a personalized showcase demo specifically for you to illustrate this: https://demo.claraverse.in/aniket-kanade-photography. Would love to get your feedback on this.",
    "slug": "aniket-kanade-photography"
  },
  {
    "id": 513,
    "name": "Eyes Pixel Photography",
    "founder": "Setu Raj",
    "city": "Pune",
    "category": "Wedding/Event/Product",
    "instagram": "@eyespixel",
    "websiteStatus": "Has website (eyespixel.com) — NO booking form",
    "phone": "—",
    "email": "—",
    "notes": "Lead photographer Setu Raj. Pre-wedding, wedding, event, product, food, newborn. No booking.",
    "url": "https://demo.claraverse.in/eyes-pixel-photography",
    "pitch": "Hey Setu Raj, Your portfolio at Eyes Pixel Photography, especially the heartwarming newborn shots and vibrant wedding captures, truly stands out with its beautiful storytelling. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've built a personalized showcase demo specifically for you to illustrate how seamless this could be: https://demo.claraverse.in/eyes-pixel-photography Would love to get your feedback on this.",
    "slug": "eyes-pixel-photography"
  },
  {
    "id": 514,
    "name": "WedMeGood Pune Photographers",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "Varies",
    "websiteStatus": "Directory (wedmegood.com)",
    "phone": "—",
    "email": "vendors@wedmegood.com",
    "notes": "183 wedding photographers listed. Directory approach. No direct booking.",
    "url": "https://demo.claraverse.in/wedmegood-pune-photographers",
    "pitch": "Hey Team, we're really impressed with the extensive and diverse collection of wedding photographers you've curated for Pune. I noticed your directory approach means individual photographers might lack a streamlined online booking system, potentially leading to manual booking processes. We've built a personalized showcase demo specifically for WedMeGood Pune Photographers to illustrate how this could work: https://demo.claraverse.in/wedmegood-pune-photographers. Would love to get your feedback on this.",
    "slug": "wedmegood-pune-photographers"
  },
  {
    "id": 515,
    "name": "Edita Photography",
    "founder": "Edita Paluri",
    "city": "Pune",
    "category": "Newborn/Maternity",
    "instagram": "@editaphotography",
    "websiteStatus": "Has website (editaphotography.in) — NO booking form",
    "phone": "+91-9922412417",
    "email": "—",
    "notes": "Lithuanian photographer settled in Pune. Maternity, newborn, baby, child. Packages from ₹20K. Phone verified.",
    "url": "https://demo.claraverse.in/edita-photography",
    "pitch": "Hey Edita, Your beautiful newborn and maternity photography truly captures such precious moments, and your unique Lithuanian perspective in Pune shines through your portfolio. I noticed your website, editaphotography.in, doesn't have an online booking system, which likely means you're handling all inquiries and bookings manually. We've actually put together a personalized showcase demo for Edita Photography to illustrate how seamless this could be: https://demo.claraverse.in/edita-photography Would love to get your feedback on this.",
    "slug": "edita-photography"
  },
  {
    "id": 516,
    "name": "Vaishali Harip Photography",
    "founder": "Vaishali Harip",
    "city": "Pune",
    "category": "Newborn/Maternity",
    "instagram": "@vaishaliharip",
    "websiteStatus": "Has website (vaishaliharip.com) — NO booking form",
    "phone": "—",
    "email": "contact@vaishaliharip.com",
    "notes": "Newborn & maternity specialist. Natural light. Email verified.",
    "url": "https://demo.claraverse.in/vaishali-harip-photography",
    "pitch": "Hey Vaishali, Your natural light newborn and maternity photography at Vaishali Harip Photography is truly beautiful and captures such tender moments. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've actually built a personalized showcase demo specifically for you to illustrate how seamless this could be: https://demo.claraverse.in/vaishali-harip-photography. Would love to get your feedback on this.",
    "slug": "vaishali-harip-photography"
  },
  {
    "id": 517,
    "name": "Deep Achtani Photography",
    "founder": "Deep & Amrita Achtani",
    "city": "Pune (Viman Nagar)",
    "category": "Newborn/Maternity/Family",
    "instagram": "@deepachtani",
    "websiteStatus": "Has website (deepachtani.com) — NO booking form",
    "phone": "+91-9021709825",
    "email": "amrita.achtani@gmail.com",
    "notes": "Studio in Viman Nagar. Newborn, maternity, kids. Phone + email verified.",
    "url": "https://demo.claraverse.in/deep-achtani-photography",
    "pitch": "Hey Deep & Amrita, Your beautiful newborn, maternity, and family photography truly captures precious moments with such warmth and artistry. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've built a personalized showcase demo specifically for Deep Achtani Photography to illustrate how this works: https://demo.claraverse.in/deep-achtani-photography. Would love to get your feedback on this.",
    "slug": "deep-achtani-photography"
  },
  {
    "id": 518,
    "name": "Lil Starz Photography",
    "founder": "Pradeep",
    "city": "Pune",
    "category": "Newborn/Baby",
    "instagram": "@lilstarz",
    "websiteStatus": "Has website (lilstarz.in) — NO booking form",
    "phone": "—",
    "email": "—",
    "notes": "Children's portraiture & newborn. Sleepy curled poses. No booking.",
    "url": "https://demo.claraverse.in/lil-starz-photography",
    "pitch": "Hey Pradeep, Your newborn and children's portraits, especially those sleepy curled poses, are absolutely heartwarming and capture such precious moments. I noticed your website, lilstarz.in, doesn't currently offer an online booking system, which often means managing inquiries and scheduling manually. We've actually put together a quick, personalized demo for Lil Starz Photography at https://demo.claraverse.in/lil-starz-photography to show how seamless this could be. Would love to get your feedback on this.",
    "slug": "lil-starz-photography"
  },
  {
    "id": 519,
    "name": "The Kids Photos",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Baby/Family",
    "instagram": "@thekidsphotos",
    "websiteStatus": "Has website (thekidsphotos.com) — NO booking form",
    "phone": "—",
    "email": "—",
    "notes": "Newborn, baby, maternity & family photography. No booking system.",
    "url": "https://demo.claraverse.in/the-kids-photos",
    "pitch": "Hey Team, Your newborn, baby, and family photography at The Kids Photos truly captures those precious early moments with such warmth and authenticity. I noticed your website, thekidsphotos.com, doesn't currently feature an online booking system, which often means managing inquiries and scheduling manually. We've actually put together a personalized showcase demo for The Kids Photos to illustrate how seamless this could be: https://demo.claraverse.in/the-kids-photos. Would love to get your feedback on this.",
    "slug": "the-kids-photos"
  },
  {
    "id": 520,
    "name": "JustDial Newborn Baby Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Baby",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory of newborn photographers. JustDial listed.",
    "url": "https://demo.claraverse.in/justdial-newborn-baby-photographers-pune",
    "pitch": "Hey Team, Your platform's dedication to showcasing talented newborn photographers in Pune is truly commendable, providing a valuable resource for new parents. While JustDial helps connect clients, I imagine managing inquiries and bookings for the photographers listed can still be a manual process. We've actually built a personalized showcase demo specifically for JustDial Newborn Baby Photographers Pune to illustrate how an integrated system could streamline this: https://demo.claraverse.in/justdial-newborn-baby-photographers-pune. Would love to get your feedback on this.",
    "slug": "justdial-newborn-baby-photographers-pune"
  },
  {
    "id": 521,
    "name": "Sandeep Khade Studios",
    "founder": "Sandeep Khade",
    "city": "Pune (Baner)",
    "category": "Portrait/Headshot/Commercial",
    "instagram": "@sandeepkhade",
    "websiteStatus": "Has website (sandeepkhadestudios.com) — NO booking form",
    "phone": "+91-8412011220",
    "email": "—",
    "notes": "Since 2009. Corporate headshots, personal branding, LinkedIn, matrimonial, family, real estate. Phone verified.",
    "url": "https://demo.claraverse.in/sandeep-khade-studios",
    "pitch": "Hey Sandeep, your corporate headshots and personal branding work truly stand out, capturing professionalism and personality beautifully. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've actually built a personalized showcase demo for Sandeep Khade Studios to illustrate exactly how this works: https://demo.claraverse.in/sandeep-khade-studios. Would love to get your feedback on this.",
    "slug": "sandeep-khade-studios"
  },
  {
    "id": 522,
    "name": "The Portrait Studio Pune",
    "founder": "Aun'ali Dhariwal",
    "city": "Pune (East Street)",
    "category": "Portrait/Family",
    "instagram": "@theportraitstudio",
    "websiteStatus": "Has website (theportraitstudio.in) — NO booking form",
    "phone": "+91-8928994242",
    "email": "support@theportraitstudio.in",
    "notes": "Kumar Pavilion, East Street. Family & portrait. Phone + email verified.",
    "url": "https://demo.claraverse.in/the-portrait-studio-pune",
    "pitch": "Hey Aun'ali Dhariwal, I'm truly impressed by the warm and authentic family portraits you capture at The Portrait Studio Pune, especially the way you bring out genuine emotions. I noticed your website, theportraitstudio.in, currently lacks an online booking system, meaning bookings are likely handled manually. We've actually built a personalized showcase demo specifically for The Portrait Studio Pune to illustrate how seamless online bookings could be: https://demo.claraverse.in/the-portrait-studio-pune Would love to get your feedback on this.",
    "slug": "the-portrait-studio-pune"
  },
  {
    "id": 523,
    "name": "Studio Panorama / Abhiram Tilak",
    "founder": "Abhiram Tilak",
    "city": "Pune (Erandawana)",
    "category": "Portrait/Fashion/Portfolio",
    "instagram": "@abhiramtilak",
    "websiteStatus": "Has website (studiopanorama.com) — NO booking form",
    "phone": "+91-9823019057",
    "email": "—",
    "notes": "203 Business Guild, Law College Road. Fashion, portfolio, portrait, product, training. Phone verified.",
    "url": "https://demo.claraverse.in/studio-panorama-abhiram-tilak",
    "pitch": "Hey Abhiram Tilak, Your portfolio at Studio Panorama, especially your fashion and portrait work, truly stands out with its distinctive style and professional execution. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've actually built a personalized showcase demo specifically for Studio Panorama to illustrate how seamlessly this could work for you: https://demo.claraverse.in/studio-panorama-abhiram-tilak. Would love to get your feedback on this.",
    "slug": "studio-panorama-abhiram-tilak"
  },
  {
    "id": 524,
    "name": "Sulekha Family Portrait Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Family",
    "instagram": "Varies",
    "websiteStatus": "Directory (sulekha.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Supernova Studio, Twogetherfilms, etc. listed.",
    "url": "https://demo.claraverse.in/sulekha-family-portrait-photographers-pune",
    "pitch": "Hey Team, Your focus on capturing beautiful family portraits really stands out. I noticed that managing inquiries and bookings through a directory listing can often be a manual process, potentially missing out on direct client engagement. We've actually put together a personalized showcase demo for you at https://demo.claraverse.in/sulekha-family-portrait-photographers-pune to illustrate how a dedicated platform could streamline this. Would love to get your feedback on this.",
    "slug": "sulekha-family-portrait-photographers-pune"
  },
  {
    "id": 525,
    "name": "JustDial Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/General",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "7675 photo studios listed. Aditis Photos, Bhushan Photo Studio, etc.",
    "url": "https://demo.claraverse.in/justdial-photographers-pune",
    "pitch": "Hey Team, We're really impressed by the diverse range of portrait and general photography styles showcased by the studios listed on JustDial Photographers Pune. We noticed that while JustDial helps connect customers, individual studios often manage bookings manually, which can be time-consuming. We've actually built a personalized showcase demo specifically for the studios listed on JustDial Photographers Pune to streamline this process: https://demo.claraverse.in/justdial-photographers-pune. Would love to get your feedback on this.",
    "slug": "justdial-photographers-pune"
  },
  {
    "id": 526,
    "name": "CelebU Studio",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/E-commerce",
    "instagram": "@celebustudio",
    "websiteStatus": "Has website (celebustudio.com) — NO booking form",
    "phone": "+91-8888999653",
    "email": "—",
    "notes": "Product photography for e-commerce. Amazon-ready. Phone verified.",
    "url": "https://demo.claraverse.in/celebu-studio",
    "pitch": "Hey Team, Your product photography for e-commerce, especially the Amazon-ready focus, truly stands out for its clarity and commercial appeal. I noticed your website, celebustudio.com, currently lacks an online booking system, which likely means bookings are handled manually. We've built a personalized showcase demo specifically for CelebU Studio to illustrate how seamless this could be: https://demo.claraverse.in/celebu-studio Would love to get your feedback on this.",
    "slug": "celebu-studio"
  },
  {
    "id": 527,
    "name": "Bring It Online",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Fashion/E-commerce",
    "instagram": "@bringitonline",
    "websiteStatus": "Has website (bringitonline.in) — NO booking form",
    "phone": "+91-9319989802",
    "email": "letstalk@bringitonline.in",
    "notes": "Fashion & product photography. E-commerce focus. Phone + email verified.",
    "url": "https://demo.claraverse.in/bring-it-online",
    "pitch": "Hey Team, I'm really impressed by the sleek and professional fashion and product photography showcased by Bring It Online. I noticed your website (bringitonline.in) doesn't have an online booking system, which often means handling bookings manually. We've actually built a personalized showcase demo specifically for Bring It Online to illustrate how seamless this could be: https://demo.claraverse.in/bring-it-online. Would love to get your feedback on this.",
    "slug": "bring-it-online"
  },
  {
    "id": 528,
    "name": "The Lens India",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Commercial",
    "instagram": "@thelensindia",
    "websiteStatus": "Has website (thelensindia.com) — NO booking form",
    "phone": "+91-8308809875",
    "email": "contactus@thelensindia.com",
    "notes": "Product photography studio & lifestyle shoots. Phone + email verified.",
    "url": "https://demo.claraverse.in/the-lens-india",
    "pitch": "Hey Team, We're truly impressed by the crisp product photography and vibrant lifestyle shoots showcased on your website. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've built a personalized showcase demo for The Lens India to illustrate how this could streamline your operations: https://demo.claraverse.in/the-lens-india Would love to get your feedback on this.",
    "slug": "the-lens-india"
  },
  {
    "id": 529,
    "name": "KS Studio",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Commercial",
    "instagram": "@ksstudiophoto",
    "websiteStatus": "Has website (ksstudiophoto.com) — NO booking form",
    "phone": "+91-9063095559",
    "email": "info@ksstudiophoto.com",
    "notes": "Product + commercial. E-commerce focus. Phone + email + WhatsApp verified.",
    "url": "https://demo.claraverse.in/ks-studio",
    "pitch": "Hey Team, Your focus on product and commercial photography, especially for e-commerce, truly stands out. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've built a personalized showcase demo specifically for KS Studio to illustrate how seamless this could be: https://demo.claraverse.in/ks-studio. Would love to get your feedback on this.",
    "slug": "ks-studio"
  },
  {
    "id": 530,
    "name": "IndiaMart Product Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Commercial",
    "instagram": "Varies",
    "websiteStatus": "Directory (indiamart.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory of product photography services. Multiple vendors.",
    "url": "https://demo.claraverse.in/indiamart-product-photography-pune",
    "pitch": "Hey Team, I'm genuinely impressed by the comprehensive directory of product photography services you offer through IndiaMart Product Photography Pune, showcasing a wide array of styles and specializations. I noticed that coordinating inquiries and bookings for multiple vendors via a directory can often lead to manual processes and potential missed opportunities. We've actually built a personalized showcase demo specifically for IndiaMart Product Photography Pune to illustrate how a more streamlined client acquisition and management system could work: https://demo.claraverse.in/indiamart-product-photography-pune. Would love to get your feedback on this.",
    "slug": "indiamart-product-photography-pune"
  },
  {
    "id": 531,
    "name": "Visual Krishna Photography",
    "founder": "Krishna",
    "city": "Pune (Aundh/Hinjewadi/Baner/Kharadi)",
    "category": "Corporate/Event",
    "instagram": "@visualkrishna",
    "websiteStatus": "Has website (visualkrishna.com) — NO booking form",
    "phone": "+91-8208031265",
    "email": "—",
    "notes": "87+ five-star reviews. 100+ corporate events. Conference, seminar, AGM. Phone verified.",
    "url": "https://demo.claraverse.in/visual-krishna-photography",
    "pitch": "Hey Krishna, Your portfolio showcasing 100+ corporate events, from conferences to AGMs, truly highlights your exceptional skill in capturing professional moments. I noticed your website (visualkrishna.com) lacks an online booking system, meaning bookings are likely handled manually. We've built a personalized showcase demo specifically for Visual Krishna Photography to illustrate how seamless this could be: https://demo.claraverse.in/visual-krishna-photography. Would love to get your feedback on this.",
    "slug": "visual-krishna-photography"
  },
  {
    "id": 532,
    "name": "EventGraphia",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@eventgraphia",
    "websiteStatus": "Has website (eventgraphia.com) — NO booking form",
    "phone": "+91-8368325054 / +91-8851860556",
    "email": "info@eventgraphia.com",
    "notes": "Corporate event photographers. Phone + email verified.",
    "url": "https://demo.claraverse.in/eventgraphia",
    "pitch": "Hey Team, Your corporate event photography at EventGraphia beautifully captures the energy and essence of each occasion. I noticed your website, eventgraphia.com, currently handles bookings manually, which can be quite time-consuming. We've actually built a personalized showcase demo specifically for EventGraphia to illustrate how an integrated booking system could streamline your operations: https://demo.claraverse.in/eventgraphia Would love to get your feedback on this.",
    "slug": "eventgraphia"
  },
  {
    "id": 533,
    "name": "Rakesh Tatia Photography",
    "founder": "Rakesh Tatia",
    "city": "Pune",
    "category": "Event/Corporate",
    "instagram": "@rakeshtatia",
    "websiteStatus": "Has website (rakeshtatiaphotography.com) — NO booking form",
    "phone": "—",
    "email": "—",
    "notes": "Event photographer. Phone & WhatsApp contact on site. No booking form.",
    "url": "https://demo.claraverse.in/rakesh-tatia-photography",
    "pitch": "Hey Rakesh, Your event photography portfolio truly captures the essence and energy of each occasion with a vibrant, storytelling approach. I noticed your website, rakeshtatiaphotography.com, doesn't currently feature an online booking system, which often means managing inquiries manually. We've actually put together a quick, personalized demo for Rakesh Tatia Photography to show how seamless online bookings could look for you: https://demo.claraverse.in/rakesh-tatia-photography. Would love to get your feedback on this.",
    "slug": "rakesh-tatia-photography"
  },
  {
    "id": 534,
    "name": "IndiaMart Corporate Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "Varies",
    "websiteStatus": "Directory (indiamart.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Arham Enterprises, Kothrud. Multiple vendors listed.",
    "url": "https://demo.claraverse.in/indiamart-corporate-photography-pune",
    "pitch": "Hey Team, I'm really impressed by your focus on capturing professional corporate and event moments, which is so crucial for businesses today. I noticed that being part of a directory means you might be missing out on a dedicated online presence with features like an integrated booking system, which can make managing inquiries quite manual. We've actually built a personalized showcase demo specifically for you to illustrate how this could work: https://demo.claraverse.in/indiamart-corporate-photography-pune. Would love to get your feedback on this.",
    "slug": "indiamart-corporate-photography-pune"
  },
  {
    "id": 535,
    "name": "Sulekha Corporate Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "Varies",
    "websiteStatus": "Directory (sulekha.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Supernova Studio, Twogetherfilms, Shirish Sherekar, etc.",
    "url": "https://demo.claraverse.in/sulekha-corporate-photographers-pune",
    "pitch": "Hey Team, We're truly impressed by the diverse and professional corporate and event photography showcased by Sulekha Corporate Photographers Pune. We noticed that while you're featured on Sulekha, having a dedicated online presence can significantly enhance your reach and streamline client interactions, which might be challenging on a directory platform. We've built a personalized showcase demo for you to illustrate this: https://demo.claraverse.in/sulekha-corporate-photographers-pune. Would love to get your feedback on this.",
    "slug": "sulekha-corporate-photographers-pune"
  },
  {
    "id": 536,
    "name": "ZoopGo Corporate Event Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "Varies",
    "websiteStatus": "Directory (zoopgo.com)",
    "phone": "8800825619",
    "email": "support@zoopgo.com",
    "notes": "Directory. Toll Free: 8800825619. Email verified.",
    "url": "https://demo.claraverse.in/zoopgo-corporate-event-photographers-pune",
    "pitch": "Hey Team, Your work at ZoopGo Corporate Event Photographers Pune, as showcased on your directory, clearly highlights a strong capability in capturing the dynamic and professional atmosphere of corporate events. We understand that operating within a directory can sometimes make direct client engagement and booking management a more manual process. To demonstrate how a dedicated platform could enhance your client experience and streamline operations, we've prepared a personalized showcase demo for you here: https://demo.claraverse.in/zoopgo-corporate-event-photographers-pune. We'd be keen to hear your thoughts on it.",
    "slug": "zoopgo-corporate-event-photographers-pune"
  },
  {
    "id": 537,
    "name": "JustDial Event Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Event/Corporate",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory of event photographers. Multiple vendors.",
    "url": "https://demo.claraverse.in/justdial-event-photographers-pune",
    "pitch": "Hey Team, We're really impressed by the comprehensive range of event photography services you connect clients with through JustDial Event Photographers Pune, covering such a diverse array of styles and occasions. We noticed that managing inquiries and bookings for multiple vendors through a directory can often be a manual and time-consuming process. We've put together a personalized demo for you at https://demo.claraverse.in/justdial-event-photographers-pune to show how we can streamline this for your listed photographers and clients. Would love to get your feedback on this.",
    "slug": "justdial-event-photographers-pune"
  },
  {
    "id": 538,
    "name": "Dazz Photography",
    "founder": "Team",
    "city": "Pune (Pimpri Chinchwad/Lonavala)",
    "category": "Fashion/Portfolio",
    "instagram": "@dazzphotography",
    "websiteStatus": "Has website (dazzphotography.com) — NO booking form",
    "phone": "+91-9577070700",
    "email": "info@dazzphotography.com",
    "notes": "Fashion photographer. Office B-11, Optimus Society. Phone + email verified.",
    "url": "https://demo.claraverse.in/dazz-photography",
    "pitch": "Hey Team, We're truly impressed by the stunning fashion photography and portfolio work showcased on Dazz Photography's website. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've built a personalized demo specifically for Dazz Photography to illustrate how seamless online booking could look: https://demo.claraverse.in/dazz-photography. Would love to get your feedback on this.",
    "slug": "dazz-photography"
  },
  {
    "id": 539,
    "name": "CKstudio Pune",
    "founder": "Prince",
    "city": "Pune",
    "category": "Fashion/E-commerce",
    "instagram": "@ckstudio.in",
    "websiteStatus": "Has website (ckstudio.in) — NO booking form",
    "phone": "+91-8700258773",
    "email": "info@ckstudio.in",
    "notes": "9+ years. ₹400 per apparel. Amazon/Flipkart/Myntra. Phone + email verified.",
    "url": "https://demo.claraverse.in/ckstudio-pune",
    "pitch": "Hey Prince, Your e-commerce photography for brands like Amazon, Flipkart, and Myntra really stands out, showcasing a keen eye for detail and commercial appeal. I noticed your website, ckstudio.in, doesn't currently offer an online booking system, which often means managing inquiries and bookings manually. We've put together a quick, personalized demo for CKstudio Pune to illustrate how seamless online bookings could look for you: https://demo.claraverse.in/ckstudio-pune. Would love to get your feedback on this.",
    "slug": "ckstudio-pune"
  },
  {
    "id": 540,
    "name": "Muse Photography Studios",
    "founder": "Surbhi Jain",
    "city": "Pune (Camp)",
    "category": "Fashion/Studio Rental",
    "instagram": "@musephotographystudiospune",
    "websiteStatus": "Has website (surbhijainphotography.com) — NO booking form",
    "phone": "+91-9356021272",
    "email": "surbhijainphotography@gmail.com",
    "notes": "697 Taboot St, Camp. 830 sq ft studio. UAL London, LCF Masters. Phone + email + GPay verified.",
    "url": "https://demo.claraverse.in/muse-photography-studios",
    "pitch": "Hey Surbhi, I'm truly impressed by the professional studio space and the fashion/studio rental services Muse Photography Studios offers. I noticed your website (surbhijainphotography.com) lacks an online booking system, meaning bookings are likely handled manually. We've actually built a personalized showcase demo specifically for Muse Photography Studios to show how this works: https://demo.claraverse.in/muse-photography-studios. Would love to get your feedback on this.",
    "slug": "muse-photography-studios"
  },
  {
    "id": 541,
    "name": "IndiaMart Fashion Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Portfolio",
    "instagram": "Varies",
    "websiteStatus": "Directory (indiamart.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory of fashion photography providers. Multiple vendors.",
    "url": "https://demo.claraverse.in/indiamart-fashion-photography-pune",
    "pitch": "Hey Team, I'm really impressed by the diverse range of fashion and portfolio photography showcased through IndiaMart Fashion Photography Pune. I noticed that managing inquiries and bookings for the various photographers listed on your platform might still involve a lot of manual coordination. We've actually built a personalized showcase demo specifically for IndiaMart Fashion Photography Pune to illustrate how this could be streamlined: https://demo.claraverse.in/indiamart-fashion-photography-pune. Would love to get your feedback on this.",
    "slug": "indiamart-fashion-photography-pune"
  },
  {
    "id": 542,
    "name": "JustDial Fashion Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Portfolio",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Bhushan Photo Studio, Vidisha Biz, etc. listed.",
    "url": "https://demo.claraverse.in/justdial-fashion-photographers-pune",
    "pitch": "Hey Team, We're truly impressed by the diverse and creative fashion and portfolio work showcased by JustDial Fashion Photographers Pune. We noticed that being on a directory might mean managing inquiries and bookings manually, potentially without a dedicated online system. That's why we've crafted a personalized showcase demo for you at https://demo.claraverse.in/justdial-fashion-photographers-pune to illustrate how a dedicated platform could streamline your operations. We'd love to hear your thoughts on it.",
    "slug": "justdial-fashion-photographers-pune"
  },
  {
    "id": 543,
    "name": "Vikas Dutt Photography",
    "founder": "Vikas Dutt",
    "city": "Pune",
    "category": "Real Estate/Architecture",
    "instagram": "@vikasdutt",
    "websiteStatus": "Has website (vikasdutt.com) — NO booking form",
    "phone": "+91-9004058205",
    "email": "vikas@vikasdutt.com",
    "notes": "Architecture & interiors. Gurgaon, Mumbai, Delhi, Pune, Bangalore. Phone + email verified.",
    "url": "https://demo.claraverse.in/vikas-dutt-photography",
    "pitch": "Hey Vikas Dutt, your architectural and interior photography truly captures the essence and grandeur of each space, showcasing a remarkable eye for detail and composition. I noticed your website, vikasdutt.com, doesn't currently feature an online booking system, which often means managing inquiries and appointments manually. We've actually put together a personalized showcase demo for Vikas Dutt Photography to illustrate how seamless online bookings could be: https://demo.claraverse.in/vikas-dutt-photography. Would love to get your feedback on this.",
    "slug": "vikas-dutt-photography"
  },
  {
    "id": 544,
    "name": "StudioOnCloud Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Real Estate/Architecture",
    "instagram": "@studiooncloud",
    "websiteStatus": "Has website (studiooncloud.com) — NO booking form",
    "phone": "+91-7777061955",
    "email": "studio@studiooncloud.com",
    "notes": "Real estate photography. Mumbai HQ, serves Pune. Phone + email verified.",
    "url": "https://demo.claraverse.in/studiooncloud-pune",
    "pitch": "Hey Team, Your real estate photography for StudioOnCloud Pune truly captures the essence and detail of properties, showcasing them beautifully. I noticed your website lacks an online booking system, meaning bookings are likely handled manually, which can be time-consuming. We've built a personalized showcase demo specifically for StudioOnCloud Pune to illustrate how an integrated booking system could streamline your operations: https://demo.claraverse.in/studiooncloud-pune. Would love to get your feedback on this.",
    "slug": "studiooncloud-pune"
  },
  {
    "id": 545,
    "name": "Houzz Real Estate Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Real Estate/Architecture",
    "instagram": "Varies",
    "websiteStatus": "Directory (houzz.in)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Sadik Shaikh, Yogesh Mahamuni, Royan's, etc.",
    "url": "https://demo.claraverse.in/houzz-real-estate-photography-pune",
    "pitch": "Hey Team, Your real estate and architectural photography on Houzz truly stands out with its crisp, detailed shots that beautifully capture the essence of each property. Given your presence on a directory like Houzz, I imagine managing inquiries and bookings directly can be quite a manual process without a dedicated online system. To help streamline this, we've built a personalized showcase demo for you at https://demo.claraverse.in/houzz-real-estate-photography-pune, illustrating how a dedicated platform could enhance your client experience. Would love to get your feedback on this.",
    "slug": "houzz-real-estate-photography-pune"
  },
  {
    "id": 546,
    "name": "Royan's Photography",
    "founder": "Royan",
    "city": "Pune (Aundh)",
    "category": "Real Estate/Interior",
    "instagram": "@royansphotography",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Aundh, DP Road. Real estate & interior photography. Houzz listed.",
    "url": "https://demo.claraverse.in/royans-photography",
    "pitch": "Hey Royan, I was truly captivated by your exceptional real estate and interior photography, particularly your impressive work featured on Houzz. It seems you don't currently have a dedicated online platform to showcase your stunning portfolio and manage client inquiries efficiently. To give you a glimpse of what's possible, we've crafted a personalized demo specifically for Royan's Photography: https://demo.claraverse.in/royans-photography. I'd be thrilled to hear your thoughts on it.",
    "slug": "royans-photography"
  },
  {
    "id": 547,
    "name": "Yogesh Mahamuni Photography",
    "founder": "Yogesh Mahamuni",
    "city": "Pune",
    "category": "Architecture/Interior",
    "instagram": "@yogeshmahamuni",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Pune-based interior & architectural photographer. 5+ years exp. Houzz listed.",
    "url": "https://demo.claraverse.in/yogesh-mahamuni-photography",
    "pitch": "Hey Yogesh, Your interior and architectural photography truly captures the essence and detail of each space, showcasing a keen eye for design. I noticed you don't have a dedicated online presence to showcase your stunning work and streamline client inquiries. We've actually built a personalized showcase demo for Yogesh Mahamuni Photography to illustrate how easily you could manage bookings and display your portfolio: https://demo.claraverse.in/yogesh-mahamuni-photography. Would love to get your feedback on this.",
    "slug": "yogesh-mahamuni-photography"
  },
  {
    "id": 548,
    "name": "Evolver Media Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Interior",
    "instagram": "@evolvermedia",
    "websiteStatus": "Has website (evolvermedia.in) — NO booking form",
    "phone": "—",
    "email": "—",
    "notes": "10+ years. Interior designers, architects, restaurants, hotels.",
    "url": "https://demo.claraverse.in/evolver-media-pune",
    "pitch": "Hey Team, Your architectural and interior photography for spaces like restaurants and hotels on evolvermedia.in is truly captivating, showcasing a keen eye for detail and design. I noticed your website lacks an online booking system, meaning bookings are handled manually. We've actually built a personalized showcase demo specifically for Evolver Media Pune to illustrate how seamless this could be: https://demo.claraverse.in/evolver-media-pune. Would love to get your feedback on this.",
    "slug": "evolver-media-pune"
  },
  {
    "id": 549,
    "name": "Kartik Bakshi Photography",
    "founder": "Kartik Bakshi",
    "city": "Pune",
    "category": "Architecture/Product",
    "instagram": "@kartikbakshi",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Architectural & product photographer. Pune-based. Houzz listed.",
    "url": "https://demo.claraverse.in/kartik-bakshi-photography",
    "pitch": "Hey Kartik, Your architectural and product photography, especially as seen on Houzz, is truly impressive, showcasing a keen eye for detail and composition. I noticed you don't currently have a dedicated website, which means potential clients might miss out on seeing your full portfolio and easily connecting with you. We've put together a personalized showcase demo for Kartik Bakshi Photography to illustrate how a professional online presence could elevate your work: https://demo.claraverse.in/kartik-bakshi-photography. Would love to get your feedback on this.",
    "slug": "kartik-bakshi-photography"
  },
  {
    "id": 550,
    "name": "WedMeGood Pune Wedding Photographers",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "Varies",
    "websiteStatus": "Directory (wedmegood.com)",
    "phone": "—",
    "email": "vendors@wedmegood.com",
    "notes": "183 wedding photographers listed. Viman Nagar, 5.0 rating.",
    "url": "https://demo.claraverse.in/wedmegood-pune-wedding-photographers",
    "pitch": "Hey Team, We're truly impressed by the extensive and high-quality selection of wedding photographers you feature on WedMeGood Pune, especially with that stellar 5.0 rating in Viman Nagar. However, we've observed that managing bookings for 183 photographers across a directory can be quite a manual process, potentially lacking a centralized online booking system. To illustrate how we can streamline this, we've crafted a personalized demo for WedMeGood Pune: https://demo.claraverse.in/wedmegood-pune-wedding-photographers We'd love to get your feedback on this.",
    "slug": "wedmegood-pune-wedding-photographers"
  },
  {
    "id": 551,
    "name": "JustDial Wedding Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Top wedding photographers. Multiple vendors.",
    "url": "https://demo.claraverse.in/justdial-wedding-photographers-pune",
    "pitch": "Hey Team, I'm truly impressed by the diverse and high-quality wedding photography showcased through JustDial Wedding Photographers Pune, highlighting the incredible talent you feature. I noticed that as a directory, managing inquiries and bookings for multiple vendors can become quite manual and time-consuming without a centralized system. We've actually built a personalized showcase demo specifically for JustDial Wedding Photographers Pune to illustrate how an integrated booking and portfolio management system could streamline operations: https://demo.claraverse.in/justdial-wedding-photographers-pune Would love to get your feedback on this.",
    "slug": "justdial-wedding-photographers-pune"
  },
  {
    "id": 552,
    "name": "Sulekha Wedding Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "Varies",
    "websiteStatus": "Directory (sulekha.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Top wedding photographers. Multiple vendors.",
    "url": "https://demo.claraverse.in/sulekha-wedding-photographers-pune",
    "pitch": "Hey Team, We're truly impressed by Sulekha Wedding Photographers Pune's dedication to showcasing top wedding photography talent, making it a go-to resource for couples. We noticed your platform, while excellent for discovery, might lack an integrated online booking system for the photographers you feature, meaning bookings are often handled manually off-site. To illustrate how a streamlined system could benefit your platform and vendors, we've prepared a personalized showcase demo just for you: https://demo.claraverse.in/sulekha-wedding-photographers-pune We'd love to get your feedback on this.",
    "slug": "sulekha-wedding-photographers-pune"
  },
  {
    "id": 553,
    "name": "TimeFrame Studios",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Event",
    "instagram": "@timeframestudios",
    "websiteStatus": "Has website (timeframestudios.in) — NO booking form",
    "phone": "—",
    "email": "—",
    "notes": "Wedding & event photography. No booking system.",
    "url": "https://demo.claraverse.in/timeframe-studios",
    "pitch": "Hey Team, Your wedding and event photography truly captures the essence and joy of those special moments. I noticed your website, timeframe-studios.in, doesn't currently feature an online booking system, which often means manual handling of inquiries. We've built a personalized showcase demo specifically for TimeFrame Studios to illustrate how seamless this could be: https://demo.claraverse.in/timeframe-studios Would love to get your feedback on this.",
    "slug": "timeframe-studios"
  },
  {
    "id": 554,
    "name": "Pune Wedding Photography",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@puneweddingphotography",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Local wedding photographer. Instagram-only presence.",
    "url": "https://demo.claraverse.in/pune-wedding-photography",
    "pitch": "Hey Team, Your Instagram showcases such a beautiful, authentic capture of wedding day emotions. Given your stunning Instagram presence, I noticed you don't have a dedicated website, which might make managing inquiries and bookings a bit challenging. We've actually put together a personalized showcase demo for Pune Wedding Photography at https://demo.claraverse.in/pune-wedding-photography to illustrate how a dedicated platform could streamline things. Would love to get your feedback on this.",
    "slug": "pune-wedding-photography"
  },
  {
    "id": 555,
    "name": "Candid Wedding Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@candidweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Candid wedding specialist. Instagram-only.",
    "url": "https://demo.claraverse.in/candid-wedding-photography-pune",
    "pitch": "Hey Team, I'm genuinely impressed by the authentic and heartfelt candid moments you capture, truly telling a unique story with each wedding. I noticed you're primarily Instagram-only, which means managing inquiries and bookings might be quite manual without a dedicated online presence. We've actually put together a personalized showcase demo for Candid Wedding Photography Pune to illustrate how a dedicated platform could streamline this for you: https://demo.claraverse.in/candid-wedding-photography-pune Would love to get your feedback on this.",
    "slug": "candid-wedding-photography-pune"
  },
  {
    "id": 556,
    "name": "Pre Wedding Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Pre-Wedding/Wedding",
    "instagram": "@preweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Pre-wedding specialist. Instagram-only.",
    "url": "https://demo.claraverse.in/pre-wedding-photography-pune",
    "pitch": "Hey Team, Your Instagram-only approach to showcasing your beautiful pre-wedding photography truly captures the essence of candid moments. I noticed that without a dedicated website, managing inquiries and bookings might be a manual process, potentially missing out on direct online conversions. We've actually put together a personalized showcase demo for Pre Wedding Photography Pune to illustrate how a dedicated platform could streamline this for you: https://demo.claraverse.in/pre-wedding-photography-pune Would love to get your feedback on this.",
    "slug": "pre-wedding-photography-pune"
  },
  {
    "id": 557,
    "name": "Wedding Tales Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@weddingtalespune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Wedding storytelling. Instagram-only.",
    "url": "https://demo.claraverse.in/wedding-tales-pune",
    "pitch": "Hey Team, Your wedding storytelling on Instagram is truly captivating, capturing such genuine moments. It seems you're primarily on Instagram, which is fantastic for showcasing your work, but a dedicated online presence could help streamline inquiries and bookings beyond DMs. We've actually put together a personalized showcase demo for Wedding Tales Pune to illustrate this: https://demo.claraverse.in/wedding-tales-pune. Would love to get your feedback on this.",
    "slug": "wedding-tales-pune"
  },
  {
    "id": 558,
    "name": "Shaadi Stories Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@shaadistoriespune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/shaadi-stories-pune",
    "pitch": "Hey Team, Your Instagram-only portfolio for Shaadi Stories Pune beautifully captures the candid joy and emotion of weddings. I noticed you're operating without a dedicated website, which means you might be missing out on potential clients searching online and streamlining your booking process. We've put together a personalized showcase demo specifically for Shaadi Stories Pune to illustrate how a professional online presence can elevate your brand: https://demo.claraverse.in/shaadi-stories-pune Would love to get your feedback on this.",
    "slug": "shaadi-stories-pune"
  },
  {
    "id": 559,
    "name": "Bridal Moments Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@bridalmomentspune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Bridal & wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/bridal-moments-pune",
    "pitch": "Hey Team, I'm truly impressed by the beautiful wedding photography you showcase on Instagram. I noticed you're exclusively on Instagram, which means managing inquiries and bookings can be quite manual. We've actually built a personalized showcase demo for Bridal Moments Pune to illustrate how a dedicated platform could streamline this: https://demo.claraverse.in/bridal-moments-pune Would love to get your feedback on this.",
    "slug": "bridal-moments-pune"
  },
  {
    "id": 560,
    "name": "Baby Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Baby",
    "instagram": "@babyphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Newborn & baby photography. Instagram-only.",
    "url": "https://demo.claraverse.in/baby-photography-pune",
    "pitch": "Hey Team, Your dedication to capturing those precious early moments with your newborn and baby photography is truly heartwarming. I noticed you're currently operating without a dedicated website, which might make it challenging for potential clients to discover and book your beautiful work. We've actually put together a personalized showcase demo just for you, showing how a dedicated online presence could look: https://demo.claraverse.in/baby-photography-pune. Would love to get your feedback on this.",
    "slug": "baby-photography-pune"
  },
  {
    "id": 561,
    "name": "Maternity Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Maternity/Baby",
    "instagram": "@maternityphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Maternity & baby photography. Instagram-only.",
    "url": "https://demo.claraverse.in/maternity-photography-pune",
    "pitch": "Hey Team, Your maternity and baby photography on Instagram truly captures such precious moments with warmth and artistry. I noticed you're currently operating without a dedicated website, which means you might be missing out on potential clients searching online. We've put together a personalized showcase demo for Maternity Photography Pune to illustrate how a professional online presence could elevate your business: https://demo.claraverse.in/maternity-photography-pune Would love to get your feedback on this.",
    "slug": "maternity-photography-pune"
  },
  {
    "id": 562,
    "name": "Kids Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Child",
    "instagram": "@kidsphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Kids & child photography. Instagram-only.",
    "url": "https://demo.claraverse.in/kids-photography-pune",
    "pitch": "Hey Team, Your Instagram showcases such heartwarming and authentic moments of kids and families, truly capturing the joy of childhood. It looks like you're primarily on Instagram, which is great for showcasing your work, but it might make managing inquiries and bookings a bit more manual. We've put together a personalized showcase demo for Kids Photography Pune to illustrate how a dedicated platform could streamline this for you: https://demo.claraverse.in/kids-photography-pune. Would love to get your feedback on this.",
    "slug": "kids-photography-pune"
  },
  {
    "id": 563,
    "name": "Family Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Family/Portrait",
    "instagram": "@familyphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Family photography. Instagram-only.",
    "url": "https://demo.claraverse.in/family-photography-pune",
    "pitch": "Hey Team, We're really impressed by the heartwarming and authentic family moments you capture, as seen on your Instagram. We noticed you're currently operating without a dedicated website, which means you might be missing out on direct bookings and showcasing your beautiful work more comprehensively. To help visualize how a professional online presence could elevate your brand, we've put together a personalized demo for Family Photography Pune: https://demo.claraverse.in/family-photography-pune. We'd love to get your feedback on this.",
    "slug": "family-photography-pune"
  },
  {
    "id": 564,
    "name": "Newborn Studio Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Baby",
    "instagram": "@newbornstudiopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Newborn studio. Instagram-only.",
    "url": "https://demo.claraverse.in/newborn-studio-pune",
    "pitch": "Hey Team, Your beautiful newborn photography on Instagram truly captures those precious early moments with such warmth and artistry. I noticed you're primarily on Instagram and don't have a dedicated website, which can sometimes make it challenging for potential clients to find all your information and book easily. We've actually put together a quick personalized demo for Newborn Studio Pune to show how a dedicated online presence could look and function for you: https://demo.claraverse.in/newborn-studio-pune Would love to get your feedback on this.",
    "slug": "newborn-studio-pune"
  },
  {
    "id": 565,
    "name": "Headshot Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Headshot",
    "instagram": "@headshotpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Headshot photography. Instagram-only.",
    "url": "https://demo.claraverse.in/headshot-photography-pune",
    "pitch": "Hey Team, I was really impressed by the professional and impactful headshots you showcase on Instagram. I noticed that without a dedicated website, managing inquiries and showcasing your full portfolio might be challenging, especially since you're Instagram-only. We've put together a personalized demo for Headshot Photography Pune to illustrate how a professional online presence could elevate your brand: https://demo.claraverse.in/headshot-photography-pune. Would love to get your feedback on this.",
    "slug": "headshot-photography-pune"
  },
  {
    "id": 566,
    "name": "Corporate Headshots Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Headshot",
    "instagram": "@corporateheadshotspune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Corporate headshots. Instagram-only.",
    "url": "https://demo.claraverse.in/corporate-headshots-pune",
    "pitch": "Hey Team, Your Instagram showcases a really strong portfolio of corporate headshots, capturing professional and impactful portraits. Given your Instagram-only presence, managing inquiries and bookings might be quite manual. We've actually put together a personalized demo for Corporate Headshots Pune at https://demo.claraverse.in/corporate-headshots-pune to illustrate how a dedicated platform could streamline this. Would love to get your feedback on this.",
    "slug": "corporate-headshots-pune"
  },
  {
    "id": 567,
    "name": "LinkedIn Photos Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Headshot",
    "instagram": "@linkedinphotospune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "LinkedIn profile photos. Instagram-only.",
    "url": "https://demo.claraverse.in/linkedin-photos-pune",
    "pitch": "Hey Team, We're really impressed by the sharp, professional headshots you create for LinkedIn profiles on your Instagram. Given your strong Instagram presence but lack of a dedicated website, managing inquiries and bookings might be a manual process. We've actually put together a personalized showcase demo for LinkedIn Photos Pune to illustrate how a dedicated platform could streamline this for you: https://demo.claraverse.in/linkedin-photos-pune Would love to get your feedback on this.",
    "slug": "linkedin-photos-pune"
  },
  {
    "id": 568,
    "name": "Personal Branding Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Branding",
    "instagram": "@personalbrandingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Personal branding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/personal-branding-photography-pune",
    "pitch": "Hey Team, We're really impressed with your stunning personal branding photography showcased on Instagram. Given your strong Instagram presence, we noticed you don't have a dedicated website, which might make it challenging to manage bookings and showcase your full portfolio beyond social media. We've actually built a personalized showcase demo specifically for Personal Branding Photography Pune to illustrate how a dedicated platform could elevate your brand: https://demo.claraverse.in/personal-branding-photography-pune. We'd love to get your feedback on this.",
    "slug": "personal-branding-photography-pune"
  },
  {
    "id": 569,
    "name": "Matrimonial Photos Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Matrimonial",
    "instagram": "@matrimonialphotospune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Matrimonial & biodata photos. Instagram-only.",
    "url": "https://demo.claraverse.in/matrimonial-photos-pune",
    "pitch": "Hey Team, We're really impressed by your beautiful matrimonial and biodata photography showcased on Instagram. I noticed you're currently Instagram-only, which means managing inquiries and showcasing your full portfolio can be quite manual. We've built a personalized showcase demo specifically for Matrimonial Photos Pune to illustrate how a dedicated online presence could streamline this: https://demo.claraverse.in/matrimonial-photos-pune. Would love to get your feedback on this.",
    "slug": "matrimonial-photos-pune"
  },
  {
    "id": 570,
    "name": "E-commerce Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/E-commerce",
    "instagram": "@ecommercephotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "E-commerce product photography. Instagram-only.",
    "url": "https://demo.claraverse.in/e-commerce-photography-pune",
    "pitch": "Hey Team, Your e-commerce product photography on Instagram is truly impressive, showcasing products with such clarity and appeal. I noticed you're currently operating without a dedicated website, which might make it challenging to showcase your full portfolio and streamline client inquiries. We've put together a personalized showcase demo for E-commerce Photography Pune to illustrate how a professional online presence could look for you: https://demo.claraverse.in/e-commerce-photography-pune Would love to get your feedback on this.",
    "slug": "e-commerce-photography-pune"
  },
  {
    "id": 571,
    "name": "Amazon Product Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/E-commerce",
    "instagram": "@amazonproductpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Amazon product photography. Instagram-only.",
    "url": "https://demo.claraverse.in/amazon-product-photography-pune",
    "pitch": "Hey Team, Your Amazon product photography on Instagram truly stands out, showcasing a keen eye for detail that helps products shine. I noticed you're primarily showcasing your impressive work on Instagram, which means potential clients might miss out on a dedicated portfolio experience. We've actually built a personalized showcase demo just for you to illustrate how a dedicated platform could elevate your brand: https://demo.claraverse.in/amazon-product-photography-pune. Would love to get your feedback on this.",
    "slug": "amazon-product-photography-pune"
  },
  {
    "id": 572,
    "name": "Food Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Food",
    "instagram": "@foodphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Food photography. Instagram-only.",
    "url": "https://demo.claraverse.in/food-photography-pune",
    "pitch": "Hey Team, Your food photography on Instagram is truly captivating, showcasing dishes with such artistry and appeal. I noticed you're primarily on Instagram and don't have a dedicated website, which might make it challenging for potential clients to explore your full portfolio or book your services directly. We've put together a personalized showcase demo for Food Photography Pune to illustrate how a dedicated online presence could elevate your brand: https://demo.claraverse.in/food-photography-pune. Would love to get your feedback on this.",
    "slug": "food-photography-pune"
  },
  {
    "id": 573,
    "name": "Lifestyle Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Lifestyle",
    "instagram": "@lifestylephotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Lifestyle product photography. Instagram-only.",
    "url": "https://demo.claraverse.in/lifestyle-photography-pune",
    "pitch": "Hey Team, We're really impressed by the captivating lifestyle product photography you showcase on Instagram. Given your Instagram-only presence, we imagine managing inquiries and bookings might be quite manual. We've actually put together a personalized showcase demo for Lifestyle Photography Pune to illustrate how a dedicated online presence could streamline things: https://demo.claraverse.in/lifestyle-photography-pune. Would love to get your feedback on this.",
    "slug": "lifestyle-photography-pune"
  },
  {
    "id": 574,
    "name": "Catalog Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Catalog",
    "instagram": "@catalogphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Catalog & lookbook photography. Instagram-only.",
    "url": "https://demo.claraverse.in/catalog-photography-pune",
    "pitch": "Hey Team, Your catalog and lookbook photography on Instagram is truly impressive, showcasing products with such clarity and style. I noticed you're primarily on Instagram and don't have a dedicated website, which might make it challenging for potential clients to explore your full portfolio or book your services directly. We've actually put together a personalized showcase demo for Catalog Photography Pune to illustrate how a dedicated platform could elevate your online presence: https://demo.claraverse.in/catalog-photography-pune. Would love to get your feedback on this.",
    "slug": "catalog-photography-pune"
  },
  {
    "id": 575,
    "name": "Corporate Event Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@corporateeventpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Corporate event photography. Instagram-only.",
    "url": "https://demo.claraverse.in/corporate-event-photography-pune",
    "pitch": "Hey Team, Your corporate event photography on Instagram truly captures the energy and professionalism of each occasion. Given you're Instagram-only, managing inquiries and bookings can be quite a manual process without a dedicated online presence. We've crafted a personalized showcase demo specifically for Corporate Event Photography Pune to streamline this: https://demo.claraverse.in/corporate-event-photography-pune Would love to get your feedback on this.",
    "slug": "corporate-event-photography-pune"
  },
  {
    "id": 576,
    "name": "Conference Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@conferencephotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Conference & seminar photography. Instagram-only.",
    "url": "https://demo.claraverse.in/conference-photography-pune",
    "pitch": "Hey Team, Your focus on capturing the dynamic energy of conferences and seminars on Instagram is truly impressive. Given your incredible work is currently Instagram-only, you're missing out on a dedicated online space to showcase your portfolio and streamline client inquiries. We've built a personalized showcase demo specifically for Conference Photography Pune to illustrate how a dedicated platform could elevate your brand: https://demo.claraverse.in/conference-photography-pune Would love to get your feedback on this.",
    "slug": "conference-photography-pune"
  },
  {
    "id": 577,
    "name": "AGM Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@agmphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "AGM & corporate photography. Instagram-only.",
    "url": "https://demo.claraverse.in/agm-photography-pune",
    "pitch": "Hey Team, Your corporate and event photography on Instagram truly captures the essence of each moment with a professional and engaging style. I noticed you're currently Instagram-only, which means managing inquiries and bookings might be a manual process without a dedicated online presence. We've actually built a personalized showcase demo specifically for AGM Photography Pune to illustrate how a dedicated platform could streamline this for you: https://demo.claraverse.in/agm-photography-pune. Would love to get your feedback on this.",
    "slug": "agm-photography-pune"
  },
  {
    "id": 578,
    "name": "Product Launch Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@productlaunchpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Product launch photography. Instagram-only.",
    "url": "https://demo.claraverse.in/product-launch-photography-pune",
    "pitch": "Hey Team, Your focus on capturing the essence of product launches through your Instagram-only presence is truly impressive. I noticed you're currently operating without a dedicated website, which might make it challenging to showcase your full portfolio and streamline client inquiries. We've put together a personalized showcase demo for Product Launch Photography Pune to illustrate how a dedicated platform could elevate your brand: https://demo.claraverse.in/product-launch-photography-pune Would love to get your feedback on this.",
    "slug": "product-launch-photography-pune"
  },
  {
    "id": 579,
    "name": "Team Building Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@teambuildingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Team building & corporate photography. Instagram-only.",
    "url": "https://demo.claraverse.in/team-building-photography-pune",
    "pitch": "Hey Team, Your focus on capturing the dynamic energy of team-building and corporate events really stands out. I noticed you're currently Instagram-only, which means managing inquiries and bookings can be quite manual. We've put together a quick personalized demo at https://demo.claraverse.in/team-building-photography-pune to show how a dedicated platform could streamline this for Team Building Photography Pune. Would love to get your feedback on this.",
    "slug": "team-building-photography-pune"
  },
  {
    "id": 580,
    "name": "Model Portfolio Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Portfolio",
    "instagram": "@modelportfoliopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Model portfolio photography. Instagram-only.",
    "url": "https://demo.claraverse.in/model-portfolio-photography-pune",
    "pitch": "Hey Team, We're really impressed by the striking model portfolio photography you showcase on Instagram. Given you're Instagram-only, we noticed you might be missing out on a dedicated online space to showcase your work and streamline client bookings. We've built a personalized showcase demo specifically for Model Portfolio Photography Pune to illustrate how this could work: https://demo.claraverse.in/model-portfolio-photography-pune Would love to get your feedback on this.",
    "slug": "model-portfolio-photography-pune"
  },
  {
    "id": 581,
    "name": "Portfolio Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Portfolio",
    "instagram": "@portfoliophotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Portfolio photography. Instagram-only.",
    "url": "https://demo.claraverse.in/portfolio-photography-pune",
    "pitch": "Hey Team, Your portfolio photography on Instagram truly stands out with its striking visuals and unique aesthetic. Given your strong Instagram presence, having a dedicated online platform could significantly streamline client interactions and bookings, which currently might be handled manually. We've crafted a personalized showcase demo for Portfolio Photography Pune to illustrate this, which you can view here: https://demo.claraverse.in/portfolio-photography-pune. We'd love to get your feedback on this.",
    "slug": "portfolio-photography-pune"
  },
  {
    "id": 582,
    "name": "Beauty Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Beauty",
    "instagram": "@beautyphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Beauty & cosmetics photography. Instagram-only.",
    "url": "https://demo.claraverse.in/beauty-photography-pune",
    "pitch": "Hey Team, Your beauty & cosmetics photography on Instagram is truly captivating, showcasing a keen eye for detail and aesthetics. I noticed you're currently operating without a dedicated website, which means managing inquiries and bookings might be a manual process. We've actually put together a personalized showcase demo for Beauty Photography Pune to illustrate how a dedicated platform could streamline your operations: https://demo.claraverse.in/beauty-photography-pune Would love to get your feedback on this.",
    "slug": "beauty-photography-pune"
  },
  {
    "id": 583,
    "name": "Editorial Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Editorial",
    "instagram": "@editorialphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Editorial photography. Instagram-only.",
    "url": "https://demo.claraverse.in/editorial-photography-pune",
    "pitch": "Hey Team,\n\nI love your photography. We built a personalized booking demo for you: https://demo.claraverse.in/editorial-photography-pune\n\nWould love to get your feedback!",
    "slug": "editorial-photography-pune"
  },
  {
    "id": 584,
    "name": "Lookbook Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Lookbook",
    "instagram": "@lookbookphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Lookbook photography. Instagram-only.",
    "url": "https://demo.claraverse.in/lookbook-photography-pune",
    "pitch": "Hey Team, Your distinctive lookbook photography style on Instagram is truly captivating and showcases a unique artistic vision. I noticed that while Instagram is fantastic for sharing, not having a dedicated website might mean you're missing out on a centralized platform to present your full portfolio and streamline client inquiries. We've put together a personalized demo just for Lookbook Photography Pune to illustrate how a professional online presence could elevate your brand: https://demo.claraverse.in/lookbook-photography-pune. Would love to get your feedback on this.",
    "slug": "lookbook-photography-pune"
  },
  {
    "id": 585,
    "name": "Interior Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Interior",
    "instagram": "@interiorphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Interior photography. Instagram-only.",
    "url": "https://demo.claraverse.in/interior-photography-pune",
    "pitch": "Hey Team, Your interior photography on Instagram is truly captivating, showcasing spaces with such an artistic eye. I noticed you're currently operating without a dedicated website, which might make it challenging to showcase your full portfolio and streamline client inquiries. We've put together a personalized demo for Interior Photography Pune to illustrate how a tailored online presence could elevate your brand: https://demo.claraverse.in/interior-photography-pune. Would love to get your feedback on this.",
    "slug": "interior-photography-pune"
  },
  {
    "id": 586,
    "name": "Hotel Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Hotel",
    "instagram": "@hotelphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Hotel & resort photography. Instagram-only.",
    "url": "https://demo.claraverse.in/hotel-photography-pune",
    "pitch": "Hey Team, Your stunning hotel and resort photography on Instagram truly captures the essence and luxury of each property. I noticed you're currently operating without a dedicated website, which might make it challenging to showcase your full portfolio and streamline client inquiries. We've put together a personalized demo for Hotel Photography Pune at https://demo.claraverse.in/hotel-photography-pune to show how a professional online presence could elevate your business. Would love to get your feedback on this.",
    "slug": "hotel-photography-pune"
  },
  {
    "id": 587,
    "name": "Restaurant Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Food",
    "instagram": "@restaurantphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Restaurant & cafe photography. Instagram-only.",
    "url": "https://demo.claraverse.in/restaurant-photography-pune",
    "pitch": "Hey Team, Your Instagram showcases some truly mouth-watering restaurant and cafe photography, capturing the essence of each dish and ambiance beautifully. I noticed you're primarily on Instagram, which is fantastic for showcasing your work, but it means you might be missing out on a dedicated online space to convert inquiries into bookings seamlessly. We've put together a personalized showcase demo for Restaurant Photography Pune to illustrate how a dedicated platform could elevate your online presence and streamline your client interactions: https://demo.claraverse.in/restaurant-photography-pune Would love to get your feedback on this.",
    "slug": "restaurant-photography-pune"
  },
  {
    "id": 588,
    "name": "3D Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/3D",
    "instagram": "@3dphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "3D architectural photography. Instagram-only.",
    "url": "https://demo.claraverse.in/3d-photography-pune",
    "pitch": "Hey Team, Your 3D architectural photography on Instagram is truly impressive, capturing spaces with such unique depth and perspective. I noticed you're currently Instagram-only and don't have a dedicated website, which might make it challenging to showcase your full portfolio and streamline client inquiries. We've put together a quick personalized demo at https://demo.claraverse.in/3d-photography-pune to show how a dedicated platform could elevate your online presence. Would love to get your feedback on this.",
    "slug": "3d-photography-pune"
  },
  {
    "id": 589,
    "name": "Aerial Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Aerial",
    "instagram": "@aerialphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Aerial & drone photography. Instagram-only.",
    "url": "https://demo.claraverse.in/aerial-photography-pune",
    "pitch": "Hey Team, Your aerial and drone photography captures such breathtaking perspectives, truly standing out on Instagram. I noticed you're primarily on Instagram, which is fantastic for showcasing your work, but it can make it tricky for potential clients to find all your services and book easily. We've put together a personalized showcase demo for Aerial Photography Pune to illustrate how a dedicated online presence could elevate your client experience: https://demo.claraverse.in/aerial-photography-pune. Would love to get your feedback on this.",
    "slug": "aerial-photography-pune"
  },
  {
    "id": 590,
    "name": "Wedding Films Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Cinematography",
    "instagram": "@weddingfilmspune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Wedding cinematography. Instagram-only.",
    "url": "https://demo.claraverse.in/wedding-films-pune",
    "pitch": "Hey Team, We're truly impressed by the captivating wedding cinematography you create, beautifully showcased on Instagram. I noticed you don't have a dedicated website, which means potential clients might miss out on easily exploring your beautiful work and booking your services. We've actually built a personalized showcase demo specifically for Wedding Films Pune to illustrate how this could look: https://demo.claraverse.in/wedding-films-pune. Would love to get your feedback on this.",
    "slug": "wedding-films-pune"
  },
  {
    "id": 591,
    "name": "Cinematic Wedding Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Cinematography",
    "instagram": "@cinematicweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Cinematic wedding films. Instagram-only.",
    "url": "https://demo.claraverse.in/cinematic-wedding-pune",
    "pitch": "Hey Team, Your cinematic wedding films truly capture the emotion and grandeur of special days, creating timeless memories for your clients. I noticed you're primarily on Instagram, which is fantastic for showcasing your work, but it means potential clients might miss out on a dedicated space to explore your full portfolio and services. We've crafted a personalized showcase demo for Cinematic Wedding Pune at https://demo.claraverse.in/cinematic-wedding-pune to illustrate how a dedicated online presence could elevate your brand. Would love to get your feedback on this.",
    "slug": "cinematic-wedding-pune"
  },
  {
    "id": 592,
    "name": "Destination Wedding Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Destination",
    "instagram": "@destinationweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Destination wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/destination-wedding-pune",
    "pitch": "Hey Team, Your Instagram showcases such breathtaking destination wedding photography, truly capturing the magic of each moment. I noticed you're primarily on Instagram, which means managing inquiries and bookings might be a manual process without a dedicated website. We even built a personalized showcase demo specifically for you to show how this works: https://demo.claraverse.in/destination-wedding-pune. Would love to get your feedback on this.",
    "slug": "destination-wedding-pune"
  },
  {
    "id": 593,
    "name": "Maharashtrian Wedding Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Traditional",
    "instagram": "@maharashtrianweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Traditional Maharashtrian wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/maharashtrian-wedding-pune",
    "pitch": "Hey Team, We're truly impressed by the beautiful traditional Maharashtrian wedding photography you showcase on Instagram. Given your stunning work is Instagram-only, we noticed you might be missing out on a dedicated online presence to capture more leads and streamline bookings. We've actually put together a personalized showcase demo for Maharashtrian Wedding Pune at https://demo.claraverse.in/maharashtrian-wedding-pune to illustrate how a dedicated platform could elevate your business. We'd love to get your feedback on this.",
    "slug": "maharashtrian-wedding-pune"
  },
  {
    "id": 594,
    "name": "Marathi Wedding Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Traditional",
    "instagram": "@marathiweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Marathi wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/marathi-wedding-pune",
    "pitch": "Hey Team, Your Instagram showcases such beautiful and vibrant Marathi wedding photography, truly capturing the essence of these special celebrations. Given your incredible work is currently Instagram-only, you might be missing out on potential clients who prefer to browse a dedicated portfolio and book directly. We've actually built a personalized showcase demo specifically for Marathi Wedding Pune to illustrate how you could present your work and streamline bookings: https://demo.claraverse.in/marathi-wedding-pune Would love to get your feedback on this.",
    "slug": "marathi-wedding-pune"
  },
  {
    "id": 595,
    "name": "Pet Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Pet/Portrait",
    "instagram": "@petphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Pet photography. Instagram-only.",
    "url": "https://demo.claraverse.in/pet-photography-pune",
    "pitch": "Hey Team, Your Instagram-only approach to pet photography captures such genuine and heartwarming moments, truly showcasing the unique bond between pets and their owners. I noticed that without a dedicated website, managing inquiries and showcasing your full portfolio might be more challenging than it needs to be. We've actually put together a personalized demo for Pet Photography Pune to illustrate how a dedicated platform could streamline things for you: https://demo.claraverse.in/pet-photography-pune. Would love to get your feedback on this.",
    "slug": "pet-photography-pune"
  },
  {
    "id": 596,
    "name": "Automotive Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Automotive/Product",
    "instagram": "@automotivephotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Automotive photography. Instagram-only.",
    "url": "https://demo.claraverse.in/automotive-photography-pune",
    "pitch": "Hey Team, Your automotive photography on Instagram is truly captivating, showcasing a keen eye for detail and dynamic compositions. I noticed you're primarily Instagram-only, which means you might be missing out on a dedicated platform to showcase your stunning portfolio and streamline client inquiries. We've actually put together a personalized showcase demo just for Automotive Photography Pune to illustrate how a dedicated online presence could elevate your brand: https://demo.claraverse.in/automotive-photography-pune. Would love to get your feedback on this.",
    "slug": "automotive-photography-pune"
  },
  {
    "id": 597,
    "name": "Jewelry Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Jewelry",
    "instagram": "@jewelryphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Jewelry product photography. Instagram-only.",
    "url": "https://demo.claraverse.in/jewelry-photography-pune",
    "pitch": "Hey Team, Your jewelry product photography on Instagram is truly captivating, showcasing each piece with such exquisite detail and artistry. I noticed you're exclusively on Instagram, which is fantastic for showcasing your work, but it means potential clients might miss out on a dedicated space to explore your full portfolio and services. We've actually built a personalized showcase demo specifically for Jewelry Photography Pune to illustrate how a dedicated online presence could elevate your brand: https://demo.claraverse.in/jewelry-photography-pune. Would love to get your feedback on this.",
    "slug": "jewelry-photography-pune"
  },
  {
    "id": 598,
    "name": "Industrial Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Industrial/Commercial",
    "instagram": "@industrialphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Industrial & factory photography. Instagram-only.",
    "url": "https://demo.claraverse.in/industrial-photography-pune",
    "pitch": "Hey Team, Your industrial and factory photography captures the essence of operations with such a powerful and authentic eye. I noticed you're currently Instagram-only, which means managing inquiries and bookings can be quite a manual process. We've actually built a personalized showcase demo specifically for Industrial Photography Pune to illustrate how a dedicated online presence could streamline this: https://demo.claraverse.in/industrial-photography-pune. Would love to get your feedback on this.",
    "slug": "industrial-photography-pune"
  },
  {
    "id": 599,
    "name": "Medical Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Medical/Commercial",
    "instagram": "@medicalphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Medical & healthcare photography. Instagram-only.",
    "url": "https://demo.claraverse.in/medical-photography-pune",
    "pitch": "Hey Team, Your focus on medical and healthcare photography on Instagram is truly unique and impactful. I noticed you're currently operating without a dedicated website, which might make it challenging to showcase your full portfolio and streamline client inquiries. We've actually built a personalized showcase demo specifically for Medical Photography Pune to illustrate how a dedicated platform could elevate your online presence: https://demo.claraverse.in/medical-photography-pune. Would love to get your feedback on this.",
    "slug": "medical-photography-pune"
  }
];

const sheetsData = {
  "Pune Photographers (100 Leads)": punePhotographers100
};
