const punePhotographers100 = [
  {
    "id": 500,
    "name": "Pune Dusk Photography",
    "founder": "Abhay Lohokare",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@punedusk",
    "websiteStatus": "Has website (punedusk.com) — NO booking form",
    "phone": "+91-97679-98811",
    "email": "info@punedusk.com",
    "notes": "Founded by Abhay Lohokare (Vancouver Film School). Candid wedding & cinematic films. No online booking.",
    "url": "https://demo.claraverse.in/pune-dusk-photography",
    "pitch": "Hey Abhay,\n\nI came across Pune Dusk Photography on Instagram and absolutely love your candid wedding & cinematic film storytelling!\n\nI noticed your website, punedusk.com, doesn't have an online booking system, which often means handling inquiries manually. I've put together a quick demo for you here: https://demo.claraverse.in/pune-dusk-photography\n\nWould love to hear your thoughts on this!",
    "slug": "pune-dusk-photography",
    "facebook": "https://www.facebook.com/puneduskphotogrphy"
  },
  {
    "id": 501,
    "name": "Ajinkya Jadhav Photography",
    "founder": "Ajinkya Jadhav",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@ajinkya_jadhav_photography",
    "websiteStatus": "Has website (ajinkyajadhav.co.in) — NO booking form",
    "phone": "+91-99750-70006",
    "email": "info@ajinkyajadhav.co.in",
    "notes": "Artistic portraits & storytelling wedding coverage. No booking system.",
    "url": "https://demo.claraverse.in/ajinkya-jadhav-photography",
    "pitch": "Hey Ajinkya,\n\nFound your incredible work on Instagram and absolutely love your artistic portraits and storytelling wedding coverage!\n\nNoticed your website ajinkyajadhav.co.in doesn't have an online booking system, so I put together a quick demo at https://demo.claraverse.in/ajinkyajadhav-photography to show how you could automate this.\n\nWould love to hear your thoughts on this!",
    "slug": "ajinkya-jadhav-photography",
    "facebook": "https://www.facebook.com/ajinkyajadhavphotography"
  },
  {
    "id": 502,
    "name": "Rachna & Niranjan Photography",
    "founder": "Rachna & Niranjan",
    "city": "Pune",
    "category": "Wedding/Pre-Wedding",
    "instagram": "@rachnaniranjan_photography",
    "websiteStatus": "Has website (rachnaniranjan.com) — NO booking form",
    "phone": "+91-8983524055",
    "email": "info@rachnaniranjan.com",
    "notes": "Husband-wife duo. Documentary style. Destination weddings. Phone + email verified.",
    "url": "https://demo.claraverse.in/rachna-niranjan-photography",
    "pitch": "Hey Rachna & Niranjan,\n\nWe stumbled upon your incredible documentary-style wedding and pre-wedding photography on Instagram and were absolutely captivated by your work, especially your stunning destination wedding captures!\n\nWe noticed your beautiful website, rachnaniranjan.com, doesn't currently offer an online booking system, which often means manual scheduling. We've put together a quick demo for you at https://demo.claraverse.in/rachna-niranjan-photography to show how you could automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "rachna-niranjan-photography",
    "facebook": "https://www.facebook.com/rachnaniranjan"
  },
  {
    "id": 503,
    "name": "KnotsbyAMP",
    "founder": "Anupam and Soumi",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@knotsbyamp",
    "websiteStatus": "Has website (knotsbyamp.com) — NO booking form",
    "phone": "+91-99870-71831",
    "email": "info@knotsbyamp.com",
    "notes": "BITS Pilani & ILS Law alumni. Storytelling approach. Ritz Carlton Pune featured.",
    "url": "https://demo.claraverse.in/knotsbyamp",
    "pitch": "Hey Anupam and Soumi,\n\nLove your cinematic wedding storytelling on Instagram, especially how you capture those candid moments at places like the Ritz Carlton Pune!\n\nNoticed your website, knotsbyamp.com, doesn't have an online booking system, meaning you're likely handling inquiries manually. We've built a custom demo for KnotsbyAMP at https://demo.claraverse.in/knotsbyamp to automate and streamline your client bookings.\n\nWould love to hear your thoughts on this!",
    "slug": "knotsbyamp",
    "facebook": "www.facebook.com/KnotsbyAMP"
  },
  {
    "id": 504,
    "name": "MH12 Weddings",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Pre-Wedding",
    "instagram": "@mh12weddings",
    "websiteStatus": "Has website (mh12weddings.com) — NO booking form",
    "phone": "+91-88309-89454",
    "email": "contact@mh12weddings.com",
    "notes": "Vibrant & creative wedding photography. Candid + cinematic films. No booking.",
    "url": "https://demo.claraverse.in/mh12-weddings",
    "pitch": "Hey MH12 Weddings Team,\n\nJust stumbled upon your incredible work on Instagram and absolutely love your vibrant & creative wedding photography, especially your candid + cinematic films!\n\nNoticed you're handling bookings manually despite having a great website – imagine automating that process! I've put together a quick demo for you here: https://demo.claraverse.in/mh12-weddings\n\nWould love to hear your thoughts on this!",
    "slug": "mh12-weddings",
    "facebook": "—"
  },
  {
    "id": 505,
    "name": "Amour Affairs Photography",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@amouraffairs",
    "websiteStatus": "Has website (amouraffairs.in) — NO booking form",
    "phone": "+91-99210-00052",
    "email": "hello@amouraffairs.in",
    "notes": "Romantic storytelling & elegant wedding visuals. No online booking.",
    "url": "https://demo.claraverse.in/amour-affairs-photography",
    "pitch": "Hey Amour Affairs Team,\n\nYour ability to capture romantic storytelling and elegant wedding visuals on Instagram is truly captivating!\n\nI noticed your beautiful website (amouraffairs.in) doesn't have an online booking system, which often means manual booking processes. We've put together a tailored demo for Amour Affairs Photography here: https://demo.claraverse.in/amour-affairs-photography to show how you could automate this.\n\nWould love to hear your thoughts on this!",
    "slug": "amour-affairs-photography",
    "facebook": "—"
  },
  {
    "id": 506,
    "name": "The Picture Talk Photography",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@thepicturetalk",
    "websiteStatus": "Has website (thepicturetalk.myportfolio.com) — NO booking form",
    "phone": "+91-80478-44001",
    "email": "info@thepicturetalk.com",
    "notes": "Documentary style. Natural candid moments. myportfolio subdomain.",
    "url": "https://demo.claraverse.in/the-picture-talk-photography",
    "pitch": "Hey The Picture Talk Team,\n\nYour documentary style, natural candid wedding moments on Instagram are truly captivating!\n\nI noticed your beautiful portfolio on myportfolio.com, but it looks like you're handling bookings manually. We've put together a custom demo for you at https://demo.claraverse.in/the-picture-talk-photography to show how you can automate and streamline this.\n\nWould love to hear your thoughts on this!",
    "slug": "the-picture-talk-photography",
    "facebook": "—"
  },
  {
    "id": 507,
    "name": "Frozen Memories",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@frozenmemories.in",
    "websiteStatus": "Has website (frozenmemories.in) — NO booking form",
    "phone": "—",
    "email": "contact@frozenmemories.in",
    "notes": "Cinematic wedding storytelling. Emotional & creative visuals. No booking.",
    "url": "https://demo.claraverse.in/frozen-memories",
    "pitch": "Hey Frozen Memories Team,\n\nAbsolutely love the cinematic wedding storytelling and emotional visuals you capture on Instagram!\n\nNoticed you don't have a booking form on frozenmemories.in, which often means manual booking. We've built a custom demo for you at https://demo.claraverse.in/frozen-memories to automate this.\n\nWould love to hear your thoughts on how this could help!",
    "slug": "frozen-memories",
    "facebook": "—"
  },
  {
    "id": 508,
    "name": "Bliss Memoir Photography & Films",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@blissmemoir",
    "websiteStatus": "Has website (blissmemoir.com) — NO booking form",
    "phone": "+91 086051 13018",
    "email": "info@blissmemoir.com",
    "notes": "Warm & emotional wedding photography. Candid + artistic portraits. No booking.",
    "url": "https://demo.claraverse.in/bliss-memoir-photography-films",
    "pitch": "Hey Bliss Memoir Team,\n\nYour warm, emotional wedding photography and candid, artistic portraits on Instagram are truly captivating!\n\nI noticed your beautiful work on blissmemoir.com, but it looks like you're handling bookings manually. We've tailored a solution to automate and streamline this for you: https://demo.claraverse.in/bliss-memoir-photography-films\n\nWould love to hear your thoughts on this!",
    "slug": "bliss-memoir-photography-films",
    "facebook": "—"
  },
  {
    "id": 509,
    "name": "Capture The Image Films",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Cinematography",
    "instagram": "@capture_the_image_films",
    "websiteStatus": "No website",
    "phone": "+91-96650-57955",
    "email": "info@capturetheimagefilms.com",
    "notes": "Cinematic wedding storytelling. Instagram-only presence. No booking.",
    "url": "https://demo.claraverse.in/capture-the-image-films",
    "pitch": "Hey Team,\n\nYour cinematic wedding storytelling on Instagram is truly captivating.\n\nNo website? We built a demo to show seamless bookings & showcases: https://demo.claraverse.in/capture-the-image-films\n\nWould love your feedback!",
    "slug": "capture-the-image-films",
    "facebook": "—"
  },
  {
    "id": 510,
    "name": "The Bridal Photography",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Pre-Wedding",
    "instagram": "@thebridalphotography",
    "websiteStatus": "Has website (thebridal.photography) — NO booking form",
    "phone": "+91-8390367637",
    "email": "—",
    "notes": "Award-winning wedding & maternity. 4.9★ 1179 reviews. Packages from ₹6000. Phone verified.",
    "url": "https://demo.claraverse.in/the-bridal-photography",
    "pitch": "Hey The Bridal Photography Team,\n\nYour award-winning wedding and pre-wedding storytelling on Instagram is truly captivating!\n\nNoticed your beautiful website (thebridal.photography) doesn't have an online booking form, meaning you're likely handling inquiries manually. We've created a custom demo to automate this for you: https://demo.claraverse.in/the-bridal-photography\n\nWould love to hear your thoughts on this!",
    "slug": "the-bridal-photography",
    "facebook": "https://www.facebook.com/thebridal.photography/"
  },
  {
    "id": 511,
    "name": "Pixelworks Photography",
    "founder": "Team",
    "city": "Pune (Balewadi)",
    "category": "Wedding/Pre-Wedding",
    "instagram": "@pixelworks.in",
    "websiteStatus": "Has website (pixelworks.in) — NO booking form",
    "phone": "+91-9284880394",
    "email": "—",
    "notes": "8+ years. 100+ weddings. Balewadi studio. Phone verified. WhatsApp available.",
    "url": "https://demo.claraverse.in/pixelworks-photography",
    "pitch": "Hey Pixelworks Team,\n\nYour stunning wedding and pre-wedding photography on Instagram truly captures the magic of each couple's special day!\n\nI noticed your website, pixelworks.in, doesn't have an online booking system, meaning you're likely handling inquiries manually. We've created a tailored demo to automate this for you: https://demo.claraverse.in/pixelworks-photography\n\nWould love to hear your thoughts on this!",
    "slug": "pixelworks-photography",
    "facebook": "—"
  },
  {
    "id": 512,
    "name": "Aniket Kanade Photography",
    "founder": "Aniket Kanade",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@aniketkanade",
    "websiteStatus": "Has website (aniketkanadephotography.com) — NO booking form",
    "phone": "+91-99215-25355",
    "email": "—",
    "notes": "Best Wedding Photographer in Pune. Candid & pre-wedding specialist. No booking.",
    "url": "https://demo.claraverse.in/aniket-kanade-photography",
    "pitch": "Hey Aniket,\n\nYour stunning candid and pre-wedding shots on Instagram are truly captivating!\n\nI noticed your website, aniketkanadephotography.com, doesn't have an online booking system, meaning you're likely handling inquiries manually. I put together a quick demo for you here: https://demo.claraverse.in/aniket-kanade-photography\n\nWould love to hear your thoughts on this!",
    "slug": "aniket-kanade-photography",
    "facebook": "https://www.facebook.com/aniketkanadephotography"
  },
  {
    "id": 513,
    "name": "Eyes Pixel Photography",
    "founder": "Setu Raj",
    "city": "Pune",
    "category": "Wedding/Event/Product",
    "instagram": "@eyespixel",
    "websiteStatus": "Has website (eyespixel.com) — NO booking form",
    "phone": "+91-79032-43332",
    "email": "—",
    "notes": "Lead photographer Setu Raj. Pre-wedding, wedding, event, product, food, newborn. No booking.",
    "url": "https://demo.claraverse.in/eyes-pixel-photography",
    "pitch": "Hey Setu Raj,\n\nI came across Eyes Pixel Photography on Instagram and was genuinely impressed by your candid wedding storytelling and the incredibly creative newborn baby photoshoot setups!\n\nI noticed your website, eyespixel.com, doesn't have an online booking system, meaning you're likely handling inquiries manually. I've put together a custom demo for you at https://demo.claraverse.in/eyes-pixel-photography to show how you can automate and streamline this process.\n\nWould love to hear your thoughts on this!",
    "slug": "eyes-pixel-photography",
    "facebook": "—"
  },
  {
    "id": 514,
    "name": "WedMeGood Pune Photographers",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "Varies",
    "websiteStatus": "Directory (wedmegood.com)",
    "phone": "—",
    "email": "vendors@wedmegood.com",
    "notes": "183 wedding photographers listed. Directory approach. No direct booking.",
    "url": "https://demo.claraverse.in/wedmegood-pune-photographers",
    "pitch": "Hey WedMeGood Pune Photographers Team,\n\nJust came across your incredible wedding photography on Instagram – your ability to capture those raw, emotional moments is truly captivating!\n\nIt looks like managing bookings might be a manual process for you, especially with the directory setup, so I put together a quick demo to show how you could automate and streamline everything: https://demo.claraverse.in/wedmegood-pune-photographers\n\nWould love to hear your thoughts on this!",
    "slug": "wedmegood-pune-photographers",
    "facebook": "—"
  },
  {
    "id": 515,
    "name": "Edita Photography",
    "founder": "Edita Paluri",
    "city": "Pune",
    "category": "Newborn/Maternity",
    "instagram": "@editaphotography",
    "websiteStatus": "Has website (editaphotography.in) — NO booking form",
    "phone": "+91-9922412417",
    "email": "—",
    "notes": "Lithuanian photographer settled in Pune. Maternity, newborn, baby, child. Packages from ₹20K. Phone verified.",
    "url": "https://demo.claraverse.in/edita-photography",
    "pitch": "Hey Edita,\n\nI came across your beautiful work on Instagram, and your newborn and maternity photography is truly captivating and so beautifully composed!\n\nI noticed your website, editaphotography.in, doesn't have an online booking system, meaning you're likely handling inquiries manually. I've put together a quick demo at https://demo.claraverse.in/edita-photography to show how you could automate this.\n\nWould love to hear your thoughts on this!",
    "slug": "edita-photography",
    "facebook": "—"
  },
  {
    "id": 516,
    "name": "Vaishali Harip Photography",
    "founder": "Vaishali Harip",
    "city": "Pune",
    "category": "Newborn/Maternity",
    "instagram": "@vaishaliharip",
    "websiteStatus": "Has website (vaishaliharip.com) — NO booking form",
    "phone": "+91-91129-70708",
    "email": "contact@vaishaliharip.com",
    "notes": "Newborn & maternity specialist. Natural light. Email verified.",
    "url": "https://demo.claraverse.in/vaishali-harip-photography",
    "pitch": "Hey Vaishali Harip,\n\nYour natural light newborn and maternity photography on Instagram is absolutely breathtaking!\n\nI noticed your website doesn't have an online booking system, which means you're likely handling bookings manually. This custom demo link shows how you can automate and streamline that process: https://demo.claraverse.in/vaishali-harip-photography\n\nWould love to hear your thoughts on this!",
    "slug": "vaishali-harip-photography",
    "facebook": "https://www.facebook.com/vaishalihariphotography"
  },
  {
    "id": 517,
    "name": "Deep Achtani Photography",
    "founder": "Deep & Amrita Achtani",
    "city": "Pune (Viman Nagar)",
    "category": "Newborn/Maternity/Family",
    "instagram": "@deepachtani",
    "websiteStatus": "Has website (deepachtani.com) — NO booking form",
    "phone": "+91-9021709825",
    "email": "amrita.achtani@gmail.com",
    "notes": "Studio in Viman Nagar. Newborn, maternity, kids. Phone + email verified.",
    "url": "https://demo.claraverse.in/deep-achtani-photography",
    "pitch": "Hey Deep & Amrita,\n\nYour newborn, maternity, and family photoshoots on Instagram are truly heartwarming and beautifully captured!\n\nI noticed your website, deepachtani.com, doesn't have an online booking form, which likely means you're handling bookings manually. We've put together a quick demo for you here: https://demo.claraverse.in/deep-achtani-photography, showing how you can automate and streamline this process.\n\nWould love to hear your thoughts on this!",
    "slug": "deep-achtani-photography",
    "facebook": "—"
  },
  {
    "id": 518,
    "name": "Lil Starz Photography",
    "founder": "Pradeep",
    "city": "Pune",
    "category": "Newborn/Baby",
    "instagram": "@lilstarz",
    "websiteStatus": "Has website (lilstarz.in) — NO booking form",
    "phone": "+91-98812-09975",
    "email": "—",
    "notes": "Children's portraiture & newborn. Sleepy curled poses. No booking.",
    "url": "https://demo.claraverse.in/lil-starz-photography",
    "pitch": "Hey Pradeep,\n\nCame across Lil Starz Photography on Instagram and absolutely love your beautiful newborn and baby portraits, especially those adorable sleepy curled poses!\n\nI noticed your website, lilstarz.in, showcases your amazing work but doesn't have an online booking system, which often means manual scheduling. We've put together a quick demo at https://demo.claraverse.in/lil-starz-photography to show how you could automate and streamline your bookings.\n\nWould love to hear your thoughts on this!",
    "slug": "lil-starz-photography",
    "facebook": "—"
  },
  {
    "id": 519,
    "name": "The Kids Photos",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Baby/Family",
    "instagram": "@thekidsphotos",
    "websiteStatus": "Has website (thekidsphotos.com) — NO booking form",
    "phone": "+91-98815-81598",
    "email": "—",
    "notes": "Newborn, baby, maternity & family photography. No booking system.",
    "url": "https://demo.claraverse.in/the-kids-photos",
    "pitch": "Hey The Kids Photos Team,\n\nYour newborn, baby, and family photography on Instagram is absolutely heartwarming and beautifully captured!\n\nI noticed you have a beautiful website, but it looks like you're handling bookings manually. This custom demo shows how you could automate and streamline that process: https://demo.claraverse.in/the-kids-photos\n\nWould love to hear your thoughts on this!",
    "slug": "the-kids-photos",
    "facebook": "—"
  },
  {
    "id": 520,
    "name": "JustDial Newborn Baby Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Baby",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory of newborn photographers. JustDial listed.",
    "url": "https://demo.claraverse.in/justdial-newborn-baby-photographers-pune",
    "pitch": "Hey JustDial Newborn Baby Photographers Team,\n\nYour gentle and artistic approach to newborn photography on Instagram is truly heartwarming!\n\nIt looks like you're currently managing bookings manually through JustDial, which can be quite time-consuming. I've put together a quick demo at https://demo.claraverse.in/justdial-newborn-baby-photographers-pune to show you how you could automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "justdial-newborn-baby-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 521,
    "name": "Sandeep Khade Studios",
    "founder": "Sandeep Khade",
    "city": "Pune (Baner)",
    "category": "Portrait/Headshot/Commercial",
    "instagram": "@sandeepkhade",
    "websiteStatus": "Has website (sandeepkhadestudios.com) — NO booking form",
    "phone": "+91-8412011220",
    "email": "—",
    "notes": "Since 2009. Corporate headshots, personal branding, LinkedIn, matrimonial, family, real estate. Phone verified.",
    "url": "https://demo.claraverse.in/sandeep-khade-studios",
    "pitch": "Hey Sandeep,\n\nYour diverse portfolio, from sharp corporate headshots to warm family portraits, on Instagram is truly impressive!\n\nI noticed your website, sandeepkhadestudios.com, doesn't currently have an online booking system, meaning you're likely handling inquiries manually. We've put together a quick demo at https://demo.claraverse.in/sandeep-khade-studios to show how you could automate and streamline this.\n\nWould love to hear your thoughts on this!",
    "slug": "sandeep-khade-studios",
    "facebook": "—"
  },
  {
    "id": 522,
    "name": "The Portrait Studio Pune",
    "founder": "Aun'ali Dhariwal",
    "city": "Pune (East Street)",
    "category": "Portrait/Family",
    "instagram": "@theportraitstudio",
    "websiteStatus": "Has website (theportraitstudio.in) — NO booking form",
    "phone": "+91-8928994242",
    "email": "support@theportraitstudio.in",
    "notes": "Kumar Pavilion, East Street. Family & portrait. Phone + email verified.",
    "url": "https://demo.claraverse.in/the-portrait-studio-pune",
    "pitch": "Hey Aun'ali Dhariwal,\n\nYour ability to capture genuine emotions in family and portrait sessions on Instagram is truly remarkable!\n\nI noticed your website, theportraitstudio.in, doesn't have an online booking system, meaning you might be handling bookings manually. We've tailored a solution to automate and streamline this for you: https://demo.claraverse.in/the-portrait-studio-pune\n\nWould love to hear your thoughts on this!",
    "slug": "the-portrait-studio-pune",
    "facebook": "—"
  },
  {
    "id": 523,
    "name": "Studio Panorama / Abhiram Tilak",
    "founder": "Abhiram Tilak",
    "city": "Pune (Erandawana)",
    "category": "Portrait/Fashion/Portfolio",
    "instagram": "@abhiramtilak",
    "websiteStatus": "Has website (studiopanorama.com) — NO booking form",
    "phone": "+91-9823019057",
    "email": "—",
    "notes": "203 Business Guild, Law College Road. Fashion, portfolio, portrait, product, training. Phone verified.",
    "url": "https://demo.claraverse.in/studio-panorama-abhiram-tilak",
    "pitch": "Hey Abhiram,\n\nYour fashion and portrait work on Instagram is truly captivating!\n\nI noticed your website, studiopanorama.com, doesn't have an online booking system, meaning you're likely handling appointments manually. We've put together a custom demo for you at https://demo.claraverse.in/studio-panorama-abhiram-tilak to show how you can automate and streamline this.\n\nWould love to hear your thoughts on this!",
    "slug": "studio-panorama-abhiram-tilak",
    "facebook": "—"
  },
  {
    "id": 524,
    "name": "Sulekha Family Portrait Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Family",
    "instagram": "Varies",
    "websiteStatus": "Directory (sulekha.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Supernova Studio, Twogetherfilms, etc. listed.",
    "url": "https://demo.claraverse.in/sulekha-family-portrait-photographers-pune",
    "pitch": "Hey Team,\n\nLove your beautiful family portraits!\n\nStreamline bookings & client engagement with our platform: https://demo.claraverse.in/sulekha-family-portrait-photographers-pune\n\nFeedback welcome!",
    "slug": "sulekha-family-portrait-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 525,
    "name": "JustDial Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/General",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "7675 photo studios listed. Aditis Photos, Bhushan Photo Studio, etc.",
    "url": "https://demo.claraverse.in/justdial-photographers-pune",
    "pitch": "Hey JustDial Photographers Pune Team,\n\nI was browsing through the photography scene in Pune and was really impressed by the diverse and high-quality work showcased by studios listed on JustDial, especially the vibrant portrait and general photography you represent.\n\nIt seems like managing bookings and standing out among 7675 studios on a directory like JustDial can be quite a manual process, making it hard to capture direct client interest efficiently. I've put together a quick demo tailored for JustDial Photographers Pune that could help automate and streamline your booking process, making it super easy for clients to book directly with you: https://demo.claraverse.in/justdial-photographers-pune\n\nWould love to hear your thoughts on this!",
    "slug": "justdial-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 526,
    "name": "CelebU Studio",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/E-commerce",
    "instagram": "@celebustudio",
    "websiteStatus": "Has website (celebustudio.com) — NO booking form",
    "phone": "+91-8888999653",
    "email": "—",
    "notes": "Product photography for e-commerce. Amazon-ready. Phone verified.",
    "url": "https://demo.claraverse.in/celebu-studio",
    "pitch": "Hey CelebU Studio Team,\n\nYour e-commerce product photography on Instagram, especially the Amazon-ready shots, is truly impressive!\n\nIt looks like you're handling bookings manually, which can be time-consuming. This custom demo (https://demo.claraverse.in/celebu-studio) shows how you can automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "celebu-studio",
    "facebook": "—"
  },
  {
    "id": 527,
    "name": "Bring It Online",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Fashion/E-commerce",
    "instagram": "@bringitonline",
    "websiteStatus": "Has website (bringitonline.in) — NO booking form",
    "phone": "+91-9319989802",
    "email": "letstalk@bringitonline.in",
    "notes": "Fashion & product photography. E-commerce focus. Phone + email verified.",
    "url": "https://demo.claraverse.in/bring-it-online",
    "pitch": "Hey Bring It Online Team,\n\nYour fashion and product photography on Instagram truly captures the essence of e-commerce brands!\n\nI noticed your website, bringitonline.in, doesn't have an online booking system, meaning you're likely handling inquiries manually. This custom demo (https://demo.claraverse.in/bring-it-online) shows how you can automate and streamline that process.\n\nWould love to hear your thoughts on this!",
    "slug": "bring-it-online",
    "facebook": "—"
  },
  {
    "id": 528,
    "name": "The Lens India",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Commercial",
    "instagram": "@thelensindia",
    "websiteStatus": "Has website (thelensindia.com) — NO booking form",
    "phone": "+91-8308809875",
    "email": "contactus@thelensindia.com",
    "notes": "Product photography studio & lifestyle shoots. Phone + email verified.",
    "url": "https://demo.claraverse.in/the-lens-india",
    "pitch": "Hey The Lens India Team,\n\nI was really impressed by your stunning product photography and creative lifestyle shoots on Instagram!\n\nI noticed you don't have an online booking system on your website, which often means manual scheduling. I put together a quick demo to show how you could automate and streamline your bookings: https://demo.claraverse.in/the-lens-india\n\nWould love to hear your thoughts on this!",
    "slug": "the-lens-india",
    "facebook": "https://www.facebook.com/TheLensIndia"
  },
  {
    "id": 529,
    "name": "KS Studio",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Commercial",
    "instagram": "@ksstudiophoto",
    "websiteStatus": "Has website (ksstudiophoto.com) — NO booking form",
    "phone": "+91-9063095559",
    "email": "info@ksstudiophoto.com",
    "notes": "Product + commercial. E-commerce focus. Phone + email + WhatsApp verified.",
    "url": "https://demo.claraverse.in/ks-studio",
    "pitch": "Hey KS Studio Team,\n\nI was really impressed by the crisp, e-commerce focused product photography on your Instagram profile – it truly makes products pop!\n\nI noticed your website, ksstudiophoto.com, doesn't have an online booking system, which often means manual scheduling. This custom demo link (https://demo.claraverse.in/ks-studio) shows how you could automate that process.\n\nWould love to hear your thoughts on this!",
    "slug": "ks-studio",
    "facebook": "—"
  },
  {
    "id": 530,
    "name": "IndiaMart Product Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Commercial",
    "instagram": "Varies",
    "websiteStatus": "Directory (indiamart.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory of product photography services. Multiple vendors.",
    "url": "https://demo.claraverse.in/indiamart-product-photography-pune",
    "pitch": "Hey IndiaMart Product Photography Pune Team,\n\nLove how you capture the essence of products on Instagram, making them truly stand out!\n\nGiven you're listed on a directory like IndiaMart, managing inquiries and bookings can often be a manual process. I've put together a quick demo showing how you could automate and streamline your booking process, giving you more control and efficiency: https://demo.claraverse.in/indiamart-product-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "indiamart-product-photography-pune",
    "facebook": "—"
  },
  {
    "id": 531,
    "name": "Visual Krishna Photography",
    "founder": "Krishna",
    "city": "Pune (Aundh/Hinjewadi/Baner/Kharadi)",
    "category": "Corporate/Event",
    "instagram": "@visualkrishna",
    "websiteStatus": "Has website (visualkrishna.com) — NO booking form",
    "phone": "+91-8208031265",
    "email": "—",
    "notes": "87+ five-star reviews. 100+ corporate events. Conference, seminar, AGM. Phone verified.",
    "url": "https://demo.claraverse.in/visual-krishna-photography",
    "pitch": "Hey Krishna,\n\nI was so impressed by your corporate event photography on Instagram! The way you capture the energy of conferences and AGMs is truly exceptional.\n\nI noticed your website, visualkrishna.com, doesn't have an online booking system, meaning you're likely handling inquiries manually. This custom demo link shows how you can automate and streamline that process: https://demo.claraverse.in/visual-krishna-photography\n\nWould love to hear your thoughts on this!",
    "slug": "visual-krishna-photography",
    "facebook": "https://www.facebook.com/visualkrishnaphotography"
  },
  {
    "id": 532,
    "name": "EventGraphia",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@eventgraphia",
    "websiteStatus": "Has website (eventgraphia.com) — NO booking form",
    "phone": "+91-8368325054 / +91-8851860556",
    "email": "info@eventgraphia.com",
    "notes": "Corporate event photographers. Phone + email verified.",
    "url": "https://demo.claraverse.in/eventgraphia",
    "pitch": "Hey EventGraphia Team,\n\nI was really impressed by your corporate event photography work on Instagram! Your ability to capture the energy and professionalism of events is truly outstanding.\n\nI noticed your website, eventgraphia.com, doesn't currently have an online booking system, which often means handling inquiries and scheduling manually. I've put together a quick demo at https://demo.claraverse.in/eventgraphia to show how you could automate and streamline this process.\n\nWould love to hear your thoughts on this!",
    "slug": "eventgraphia",
    "facebook": "https://www.facebook.com/eventgraphia"
  },
  {
    "id": 533,
    "name": "Rakesh Tatia Photography",
    "founder": "Rakesh Tatia",
    "city": "Pune",
    "category": "Event/Corporate",
    "instagram": "@rakeshtatia",
    "websiteStatus": "Has website (rakeshtatiaphotography.com) — NO booking form",
    "phone": "+91-79767-37453",
    "email": "—",
    "notes": "Event photographer. Phone & WhatsApp contact on site. No booking form.",
    "url": "https://demo.claraverse.in/rakesh-tatia-photography",
    "pitch": "Hey Rakesh,\n\nYour ability to capture the energy and essence of corporate events and large-scale gatherings on Instagram is truly impressive!\n\nI noticed your website, rakeshtatiaphotography.com, relies on phone/WhatsApp for bookings, which can be time-consuming. I've put together a quick demo at https://demo.claraverse.in/rakesh-tatia-photography to show how you could automate this.\n\nWould love to hear your thoughts on this!",
    "slug": "rakesh-tatia-photography",
    "facebook": "—"
  },
  {
    "id": 534,
    "name": "IndiaMart Corporate Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "Varies",
    "websiteStatus": "Directory (indiamart.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Arham Enterprises, Kothrud. Multiple vendors listed.",
    "url": "https://demo.claraverse.in/indiamart-corporate-photography-pune",
    "pitch": "Hey IndiaMart Corporate Photography Pune Team,\n\nYour professional corporate and event photography on Instagram is truly impressive!\n\nIt looks like you're currently managing bookings manually through your IndiaMart listing. I put together a quick demo at https://demo.claraverse.in/indiamart-corporate-photography-pune to show how you could automate and streamline this.\n\nWould love to hear your thoughts on this!",
    "slug": "indiamart-corporate-photography-pune",
    "facebook": "—"
  },
  {
    "id": 535,
    "name": "Sulekha Corporate Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "Varies",
    "websiteStatus": "Directory (sulekha.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Supernova Studio, Twogetherfilms, Shirish Sherekar, etc.",
    "url": "https://demo.claraverse.in/sulekha-corporate-photographers-pune",
    "pitch": "Hey Sulekha Corporate Photographers Pune Team,\n\nYour corporate and event photography on Instagram is truly impressive, capturing the essence and professionalism of every occasion!\n\nIt looks like you're currently managing bookings manually through your directory listing, which can be time-consuming. I've put together a quick demo at https://demo.claraverse.in/sulekha-corporate-photographers-pune to show how you can automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "sulekha-corporate-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 536,
    "name": "ZoopGo Corporate Event Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "Varies",
    "websiteStatus": "Directory (zoopgo.com)",
    "phone": "8800825619",
    "email": "support@zoopgo.com",
    "notes": "Directory. Toll Free: 8800825619. Email verified.",
    "url": "https://demo.claraverse.in/zoopgo-corporate-event-photographers-pune",
    "pitch": "Hey ZoopGo Team,\n\nYour ability to capture the energy and professionalism of corporate events on Instagram is truly impressive!\n\nIt looks like you're currently managing bookings manually through your directory listing. We've tailored a quick demo to show how you can automate and streamline this process: https://demo.claraverse.in/zoopgo-corporate-event-photographers-pune\n\nWould love to hear your thoughts on this!",
    "slug": "zoopgo-corporate-event-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 537,
    "name": "JustDial Event Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Event/Corporate",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory of event photographers. Multiple vendors.",
    "url": "https://demo.claraverse.in/justdial-event-photographers-pune",
    "pitch": "Hey JustDial Event Photographers Pune Team,\n\nI was browsing Instagram and love how you connect clients with such talented event photographers in Pune!\n\nIt looks like managing inquiries and bookings for multiple event photographers through a directory can get quite manual. We've put together a quick demo at https://demo.claraverse.in/justdial-event-photographers-pune that shows how you could automate and streamline this process.\n\nWould love to hear your thoughts on this!",
    "slug": "justdial-event-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 538,
    "name": "Dazz Photography",
    "founder": "Team",
    "city": "Pune (Pimpri Chinchwad/Lonavala)",
    "category": "Fashion/Portfolio",
    "instagram": "@dazzphotography",
    "websiteStatus": "Has website (dazzphotography.com) — NO booking form",
    "phone": "+91-9577070700",
    "email": "info@dazzphotography.com",
    "notes": "Fashion photographer. Office B-11, Optimus Society. Phone + email verified.",
    "url": "https://demo.claraverse.in/dazz-photography",
    "pitch": "Hey Dazz Photography Team,\n\nYour fashion and portfolio work on Instagram is truly captivating, especially the way you capture dynamic poses and expressions!\n\nI noticed your website, dazzphotography.com, showcases your incredible work, but it looks like you might be handling bookings manually without an online system. We've put together a custom demo for Dazz Photography at https://demo.claraverse.in/dazz-photography to show how you can automate and streamline your client bookings.\n\nWould love to hear your thoughts on this!",
    "slug": "dazz-photography",
    "facebook": "https://www.facebook.com/mediacragine"
  },
  {
    "id": 539,
    "name": "CKstudio Pune",
    "founder": "Prince",
    "city": "Pune",
    "category": "Fashion/E-commerce",
    "instagram": "@ckstudio.in",
    "websiteStatus": "Has website (ckstudio.in) — NO booking form",
    "phone": "+91-8700258773",
    "email": "info@ckstudio.in",
    "notes": "9+ years. ₹400 per apparel. Amazon/Flipkart/Myntra. Phone + email verified.",
    "url": "https://demo.claraverse.in/ckstudio-pune",
    "pitch": "Hey Prince,\n\nFound your incredible fashion & e-commerce photography on Instagram! Your work for brands like Amazon, Flipkart, and Myntra truly stands out.\n\nNoticed your website, ckstudio.in, doesn't have an online booking system, meaning you're likely handling bookings manually. I've put together a quick demo at https://demo.claraverse.in/ckstudio-pune to show how you can automate and streamline this.\n\nWould love to hear your thoughts on this!",
    "slug": "ckstudio-pune",
    "facebook": "—"
  },
  {
    "id": 540,
    "name": "Muse Photography Studios",
    "founder": "Surbhi Jain",
    "city": "Pune (Camp)",
    "category": "Fashion/Studio Rental",
    "instagram": "@musephotographystudiospune",
    "websiteStatus": "Has website (surbhijainphotography.com) — NO booking form",
    "phone": "+91-9356021272",
    "email": "surbhijainphotography@gmail.com",
    "notes": "697 Taboot St, Camp. 830 sq ft studio. UAL London, LCF Masters. Phone + email + GPay verified.",
    "url": "https://demo.claraverse.in/muse-photography-studios",
    "pitch": "Hey Surbhi Jain,\n\nI came across Muse Photography Studios on Instagram and was truly impressed by your sophisticated fashion photography and the sleek aesthetic of your studio rental space!\n\nI noticed your website, surbhijainphotography.com, doesn't have an online booking system, meaning you're likely handling studio rentals and shoots manually. I've put together a custom demo here to show how you could automate this: https://demo.claraverse.in/muse-photography-studios\n\nWould love to hear your thoughts on this!",
    "slug": "muse-photography-studios",
    "facebook": "—"
  },
  {
    "id": 541,
    "name": "IndiaMart Fashion Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Portfolio",
    "instagram": "Varies",
    "websiteStatus": "Directory (indiamart.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory of fashion photography providers. Multiple vendors.",
    "url": "https://demo.claraverse.in/indiamart-fashion-photography-pune",
    "pitch": "Hey IndiaMart Fashion Photography Team,\n\nYour fashion photography work on Instagram is truly captivating, especially how you capture the essence of each model and garment!\n\nIt looks like you're listed on IndiaMart, which is great for visibility, but managing inquiries and bookings from a directory can be time-consuming and manual. I've put together a quick demo at https://demo.claraverse.in/indiamart-fashion-photography-pune to show how you could automate and streamline your booking process, making it easier for clients to book directly with you.\n\nWould love to hear your thoughts on this!",
    "slug": "indiamart-fashion-photography-pune",
    "facebook": "—"
  },
  {
    "id": 542,
    "name": "JustDial Fashion Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Portfolio",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Bhushan Photo Studio, Vidisha Biz, etc. listed.",
    "url": "https://demo.claraverse.in/justdial-fashion-photographers-pune",
    "pitch": "Hey JustDial Fashion Photographers Pune Team,\n\nYour fashion and portfolio shoots on Instagram are truly captivating!\n\nI noticed you're currently relying on directory listings for bookings. I've put together a quick demo at https://demo.claraverse.in/justdial-fashion-photographers-pune to show how you could automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "justdial-fashion-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 543,
    "name": "Vikas Dutt Photography",
    "founder": "Vikas Dutt",
    "city": "Pune",
    "category": "Real Estate/Architecture",
    "instagram": "@vikasdutt",
    "websiteStatus": "Has website (vikasdutt.com) — NO booking form",
    "phone": "+91-9004058205",
    "email": "vikas@vikasdutt.com",
    "notes": "Architecture & interiors. Gurgaon, Mumbai, Delhi, Pune, Bangalore. Phone + email verified.",
    "url": "https://demo.claraverse.in/vikas-dutt-photography",
    "pitch": "Hey Vikas Dutt,\n\nI came across Vikas Dutt Photography on Instagram and was truly impressed by your stunning architectural and interior photography, especially your work across Gurgaon, Mumbai, and Delhi!\n\nI noticed your website, vikasdutt.com, doesn't currently offer an online booking system, which often means manual booking processes. I've put together a quick demo at https://demo.claraverse.in/vikas-dutt-photography to show how you could automate and streamline this.\n\nWould love to hear your thoughts on this!",
    "slug": "vikas-dutt-photography",
    "facebook": "—"
  },
  {
    "id": 544,
    "name": "StudioOnCloud Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Real Estate/Architecture",
    "instagram": "@studiooncloud",
    "websiteStatus": "Has website (studiooncloud.com) — NO booking form",
    "phone": "+91-7777061955",
    "email": "studio@studiooncloud.com",
    "notes": "Real estate photography. Mumbai HQ, serves Pune. Phone + email verified.",
    "url": "https://demo.claraverse.in/studiooncloud-pune",
    "pitch": "Hey StudioOnCloud Pune Team,\n\nI was really impressed by the architectural detail and stunning real estate photography you showcase on Instagram!\n\nI noticed your website, studiooncloud.com, doesn't have an online booking system, meaning you're likely handling inquiries manually. I've put together a quick demo for you at https://demo.claraverse.in/studiooncloud-pune that could automate this for StudioOnCloud Pune.\n\nWould love to hear your thoughts on this!",
    "slug": "studiooncloud-pune",
    "facebook": "—"
  },
  {
    "id": 545,
    "name": "Houzz Real Estate Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Real Estate/Architecture",
    "instagram": "Varies",
    "websiteStatus": "Directory (houzz.in)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Sadik Shaikh, Yogesh Mahamuni, Royan's, etc.",
    "url": "https://demo.claraverse.in/houzz-real-estate-photography-pune",
    "pitch": "Hey Houzz Real Estate Photography Pune Team,\n\nYour eye for detail in real estate and architectural photography on Instagram is truly impressive!\n\nIt looks like you're currently managing bookings manually through your directory listing, which can be time-consuming. I've put together a custom demo at https://demo.claraverse.in/houzz-real-estate-photography-pune to show how you can automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "houzz-real-estate-photography-pune",
    "facebook": "—"
  },
  {
    "id": 546,
    "name": "Royan's Photography",
    "founder": "Royan",
    "city": "Pune (Aundh)",
    "category": "Real Estate/Interior",
    "instagram": "@royansphotography",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Aundh, DP Road. Real estate & interior photography. Houzz listed.",
    "url": "https://demo.claraverse.in/royans-photography",
    "pitch": "Hey Royan,\n\nYour real estate and interior photography on Instagram is absolutely stunning, showcasing properties with such an eye for detail!\n\nI noticed you don't have a website, which often means manual booking processes. I've put together a quick demo of how you could automate and streamline your bookings here: https://demo.claraverse.in/royans-photography\n\nWould love to hear your thoughts on this!",
    "slug": "royans-photography",
    "facebook": "—"
  },
  {
    "id": 547,
    "name": "Yogesh Mahamuni Photography",
    "founder": "Yogesh Mahamuni",
    "city": "Pune",
    "category": "Architecture/Interior",
    "instagram": "@yogeshmahamuni",
    "websiteStatus": "No website",
    "phone": "09822012548",
    "email": "—",
    "notes": "Pune-based interior & architectural photographer. 5+ years exp. Houzz listed.",
    "url": "https://demo.claraverse.in/yogesh-mahamuni-photography",
    "pitch": "Hey Yogesh,\n\nI was really impressed by your stunning architectural and interior photography on Instagram! Your eye for detail in capturing spaces is truly exceptional.\n\nGiven you don't have a website, I imagine managing inquiries and bookings can be quite manual. I've put together a quick demo at https://demo.claraverse.in/yogesh-mahamuni-photography to show how you could automate and streamline this.\n\nWould love to hear your thoughts on this!",
    "slug": "yogesh-mahamuni-photography",
    "facebook": "—"
  },
  {
    "id": 548,
    "name": "Evolver Media Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Interior",
    "instagram": "@evolvermedia",
    "websiteStatus": "Has website (evolvermedia.in) — NO booking form",
    "phone": "+91 95183 56811 (Mobile), +918047769594,5583 (WhatsApp)",
    "email": "—",
    "notes": "10+ years. Interior designers, architects, restaurants, hotels.",
    "url": "https://demo.claraverse.in/evolver-media-pune",
    "pitch": "Hey Evolver Media Team,\n\nYour stunning architectural and interior photography on Instagram truly captures the essence of space and design, especially for hotels and restaurants!\n\nI noticed your impressive website, evolvermedia.in, but it looks like you're handling bookings manually. We've created a custom demo for Evolver Media Pune at https://demo.claraverse.in/evolver-media-pune to show how you can automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "evolver-media-pune",
    "facebook": "—"
  },
  {
    "id": 549,
    "name": "Kartik Bakshi Photography",
    "founder": "Kartik Bakshi",
    "city": "Pune",
    "category": "Architecture/Product",
    "instagram": "@kartikbakshi",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Architectural & product photographer. Pune-based. Houzz listed.",
    "url": "https://demo.claraverse.in/kartik-bakshi-photography",
    "pitch": "Hey Kartik,\n\nYour architectural and product photography on Instagram is truly stunning, capturing incredible detail and perspective!\n\nI noticed you don't have a website for bookings, which can make managing inquiries tough. I've put together a quick demo at https://demo.claraverse.in/kartik-bakshi-photography to show how you could easily automate and streamline your bookings.\n\nWould love to hear your thoughts on this!",
    "slug": "kartik-bakshi-photography",
    "facebook": "—"
  },
  {
    "id": 550,
    "name": "WedMeGood Pune Wedding Photographers",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "Varies",
    "websiteStatus": "Directory (wedmegood.com)",
    "phone": "—",
    "email": "vendors@wedmegood.com",
    "notes": "183 wedding photographers listed. Viman Nagar, 5.0 rating.",
    "url": "https://demo.claraverse.in/wedmegood-pune-wedding-photographers",
    "pitch": "Hey Team,\n\nLove your impressive WedMeGood Pune photographer selection, especially Viman Nagar's 5.0 rating!\n\nStreamline manual bookings for 183 photographers? See our personalized demo: https://demo.claraverse.in/wedmegood-pune-wedding-photographers\n\nWould love your feedback!",
    "slug": "wedmegood-pune-wedding-photographers",
    "facebook": "—"
  },
  {
    "id": 551,
    "name": "JustDial Wedding Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "Varies",
    "websiteStatus": "Directory (justdial.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Top wedding photographers. Multiple vendors.",
    "url": "https://demo.claraverse.in/justdial-wedding-photographers-pune",
    "pitch": "Hey JustDial Wedding Photographers Pune Team,\n\nYour stunning wedding photography on Instagram truly captures the magic of each couple's special day!\n\nI noticed that as top wedding photographers listed on JustDial, managing inquiries and bookings across multiple vendors can get complex. This demo shows how you could automate and streamline that process: https://demo.claraverse.in/justdial-wedding-photographers-pune\n\nWould love to hear your thoughts on this!",
    "slug": "justdial-wedding-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 552,
    "name": "Sulekha Wedding Photographers Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "Varies",
    "websiteStatus": "Directory (sulekha.com)",
    "phone": "—",
    "email": "—",
    "notes": "Directory. Top wedding photographers. Multiple vendors.",
    "url": "https://demo.claraverse.in/sulekha-wedding-photographers-pune",
    "pitch": "Hey Sulekha Team,\n\nYour work as top wedding photographers on Instagram is truly captivating, especially your ability to tell unique love stories!\n\nSince you're listed on a directory, I imagine managing bookings and inquiries manually can be time-consuming. I've put together a custom demo at https://demo.claraverse.in/sulekha-wedding-photographers-pune to show how you could automate and streamline this process.\n\nWould love to hear your thoughts on this!",
    "slug": "sulekha-wedding-photographers-pune",
    "facebook": "—"
  },
  {
    "id": 553,
    "name": "TimeFrame Studios",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Event",
    "instagram": "@timeframestudios",
    "websiteStatus": "Has website (timeframestudios.in) — NO booking form",
    "phone": "+91-97644-64294",
    "email": "—",
    "notes": "Wedding & event photography. No booking system.",
    "url": "https://demo.claraverse.in/timeframe-studios",
    "pitch": "Hey TimeFrame Studios Team,\n\nLove your candid, cinematic wedding storytelling on Instagram!\n\nI noticed your beautiful website (timeframestudios.in) doesn't have an online booking system, meaning you're likely handling inquiries manually. We've created a custom demo for TimeFrame Studios at https://demo.claraverse.in/timeframestudios to show how you can automate and streamline your bookings.\n\nWould love to hear your thoughts on this!",
    "slug": "timeframe-studios",
    "facebook": "—"
  },
  {
    "id": 554,
    "name": "Pune Wedding Photography",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@puneweddingphotography",
    "websiteStatus": "No website",
    "phone": "+91-83903-67637",
    "email": "—",
    "notes": "Local wedding photographer. Instagram-only presence.",
    "url": "https://demo.claraverse.in/pune-wedding-photography",
    "pitch": "Hey Pune Wedding Photography Team,\n\nYour stunning captures of wedding moments on Instagram are truly inspiring!\n\nI noticed you don't have a website, which often means manual booking inquiries. This demo shows how you can automate and streamline that process: https://demo.claraverse.in/pune-wedding-photography\n\nWould love to hear your thoughts on this!",
    "slug": "pune-wedding-photography",
    "facebook": "https://www.facebook.com/thebridalphotography"
  },
  {
    "id": 555,
    "name": "Candid Wedding Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@candidweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Candid wedding specialist. Instagram-only.",
    "url": "https://demo.claraverse.in/candid-wedding-photography-pune",
    "pitch": "Hey Candid Wedding Photography Pune Team,\n\nLove your candid wedding photography on Instagram! Your ability to capture genuine emotions is truly remarkable.\n\nI noticed you're Instagram-only, which often means managing bookings manually. This custom demo link (https://demo.claraverse.in/candid-wedding-photography-pune) shows how you could automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "candid-wedding-photography-pune",
    "facebook": "—"
  },
  {
    "id": 556,
    "name": "Pre Wedding Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Pre-Wedding/Wedding",
    "instagram": "@preweddingpune",
    "websiteStatus": "No website",
    "phone": "+91-92848-80394",
    "email": "—",
    "notes": "Pre-wedding specialist. Instagram-only.",
    "url": "https://demo.claraverse.in/pre-wedding-photography-pune",
    "pitch": "Hey Pre Wedding Photography Pune Team,\n\nYour pre-wedding photography on Instagram is absolutely stunning – the way you capture those romantic, candid moments is truly special!\n\nSince you're Instagram-only, I noticed you might be handling bookings manually. This custom demo link shows how you could automate and streamline your booking process: https://demo.claraverse.in/pre-wedding-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "pre-wedding-photography-pune",
    "facebook": "—"
  },
  {
    "id": 557,
    "name": "Wedding Tales Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@weddingtalespune",
    "websiteStatus": "No website",
    "phone": "+91-99162-94861",
    "email": "—",
    "notes": "Wedding storytelling. Instagram-only.",
    "url": "https://demo.claraverse.in/wedding-tales-pune",
    "pitch": "Hey Wedding Tales Pune Team,\n\nYour wedding storytelling on Instagram is absolutely captivating!\n\nI noticed you're Instagram-only, which means managing inquiries and bookings can get pretty manual. This custom demo link (https://demo.claraverse.in/wedding-tales-pune) is designed to automate and streamline that for you.\n\nWould love to hear your thoughts on this!",
    "slug": "wedding-tales-pune",
    "facebook": "—"
  },
  {
    "id": 558,
    "name": "Shaadi Stories Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@shaadistoriespune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/shaadi-stories-pune",
    "pitch": "Hey Shaadi Stories Team,\n\nYour Instagram is a beautiful showcase of your wedding photography – truly captivating!\n\nI noticed you're Instagram-only, which often means manual booking processes. This custom demo link shows how you can automate and streamline everything: https://demo.claraverse.in/shaadi-stories-pune\n\nWould love to hear your thoughts on this!",
    "slug": "shaadi-stories-pune",
    "facebook": "—"
  },
  {
    "id": 559,
    "name": "Bridal Moments Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding",
    "instagram": "@bridalmomentspune",
    "websiteStatus": "No website",
    "phone": "+91-83903-67637",
    "email": "—",
    "notes": "Bridal & wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/bridal-moments-pune",
    "pitch": "Hey Bridal Moments Pune Team,\n\nI was so impressed by your stunning bridal and wedding photography on Instagram!\n\nGiven you're Instagram-only, I imagine managing bookings manually can be quite time-consuming. We've put together a custom demo for you at https://demo.claraverse.in/bridal-moments-pune to show how you can automate and streamline this process.\n\nWould love to hear your thoughts on this!",
    "slug": "bridal-moments-pune",
    "facebook": "—"
  },
  {
    "id": 560,
    "name": "Baby Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Baby",
    "instagram": "@babyphotographypune",
    "websiteStatus": "No website",
    "phone": "+91-99224-12417",
    "email": "—",
    "notes": "Newborn & baby photography. Instagram-only.",
    "url": "https://demo.claraverse.in/baby-photography-pune",
    "pitch": "Hey Baby Photography Pune Team,\n\nYour newborn baby photoshoot setups on Instagram are incredibly creative and heartwarming!\n\nI noticed you're Instagram-only, which often means manual booking inquiries – imagine automating that! I've put together a quick demo for you here: https://demo.claraverse.in/baby-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "baby-photography-pune",
    "facebook": "—"
  },
  {
    "id": 561,
    "name": "Maternity Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Maternity/Baby",
    "instagram": "@maternityphotographypune",
    "websiteStatus": "No website",
    "phone": "+91-95770-70700",
    "email": "—",
    "notes": "Maternity & baby photography. Instagram-only.",
    "url": "https://demo.claraverse.in/maternity-photography-pune",
    "pitch": "Hey Maternity Photography Pune Team,\n\nYour maternity and newborn baby photoshoot setups on Instagram are absolutely heartwarming and beautifully captured!\n\nGiven you're Instagram-only, I imagine managing bookings and inquiries manually can be quite time-consuming. I put together a quick demo link for you at https://demo.claraverse.in/maternity-photography-pune that could help automate and streamline your entire booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "maternity-photography-pune",
    "facebook": "—"
  },
  {
    "id": 562,
    "name": "Kids Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Child",
    "instagram": "@kidsphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Kids & child photography. Instagram-only.",
    "url": "https://demo.claraverse.in/kids-photography-pune",
    "pitch": "Hey Kids Photography Pune Team,\n\nYour kids and newborn photography on Instagram is absolutely heartwarming and beautifully captured!\n\nIt looks like you're currently managing bookings manually without a dedicated website. We've put together a quick demo to show how you could automate and streamline this process: https://demo.claraverse.in/kids-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "kids-photography-pune",
    "facebook": "—"
  },
  {
    "id": 563,
    "name": "Family Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Family/Portrait",
    "instagram": "@familyphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Family photography. Instagram-only.",
    "url": "https://demo.claraverse.in/family-photography-pune",
    "pitch": "Hey Team,\n\nLove your heartwarming family moments on Instagram!\n\nNo website? See your custom demo here: https://demo.claraverse.in/family-photography-pune\n\nWhat do you think?",
    "slug": "family-photography-pune",
    "facebook": "—"
  },
  {
    "id": 564,
    "name": "Newborn Studio Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Newborn/Baby",
    "instagram": "@newbornstudiopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Newborn studio. Instagram-only.",
    "url": "https://demo.claraverse.in/newborn-studio-pune",
    "pitch": "Hey Newborn Studio Pune Team,\n\nI absolutely love your newborn baby photoshoot setups on Instagram – they're incredibly creative and heartwarming!\n\nGiven you're Instagram-only, managing bookings and inquiries can get really time-consuming. I've put together a quick demo here to show how you could automate and streamline everything: https://demo.claraverse.in/newborn-studio-pune\n\nWould love to hear your thoughts on this!",
    "slug": "newborn-studio-pune",
    "facebook": "—"
  },
  {
    "id": 565,
    "name": "Headshot Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Headshot",
    "instagram": "@headshotpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Headshot photography. Instagram-only.",
    "url": "https://demo.claraverse.in/headshot-photography-pune",
    "pitch": "Hey Headshot Photography Pune Team,\n\nI found your work on Instagram and your professional headshot portfolio is truly impressive, capturing such strong and confident expressions!\n\nSince you're Instagram-only and don't have a website, I noticed you might be handling bookings manually. I've put together a quick demo of how you could automate and streamline your booking process, making it super easy for clients to schedule sessions directly: https://demo.claraverse.in/headshot-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "headshot-photography-pune",
    "facebook": "—"
  },
  {
    "id": 566,
    "name": "Corporate Headshots Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Headshot",
    "instagram": "@corporateheadshotspune",
    "websiteStatus": "No website",
    "phone": "+91-84120-11220",
    "email": "—",
    "notes": "Corporate headshots. Instagram-only.",
    "url": "https://demo.claraverse.in/corporate-headshots-pune",
    "pitch": "Hey Corporate Headshots Pune Team,\n\nYour corporate headshot portfolio on Instagram is incredibly professional and captures executive presence perfectly!\n\nI noticed you're currently Instagram-only, which often means manual booking inquiries. This demo shows how you could automate and streamline your corporate headshot bookings: https://demo.claraverse.in/corporate-headshots-pune\n\nWould love to hear your thoughts on this!",
    "slug": "corporate-headshots-pune",
    "facebook": "—"
  },
  {
    "id": 567,
    "name": "LinkedIn Photos Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Headshot",
    "instagram": "@linkedinphotospune",
    "websiteStatus": "No website",
    "phone": "+91-84120-11220",
    "email": "—",
    "notes": "LinkedIn profile photos. Instagram-only.",
    "url": "https://demo.claraverse.in/linkedin-photos-pune",
    "pitch": "Hey LinkedIn Photos Pune Team,\n\nYour LinkedIn profile photos on Instagram are incredibly sharp and professional!\n\nIt looks like you're currently managing bookings manually through Instagram DMs, which can be time-consuming. I've put together a quick demo here: https://demo.claraverse.in/linkedin-photos-pune\n\nWould love to hear your thoughts on this!",
    "slug": "linkedin-photos-pune",
    "facebook": "—"
  },
  {
    "id": 568,
    "name": "Personal Branding Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Branding",
    "instagram": "@personalbrandingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Personal branding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/personal-branding-photography-pune",
    "pitch": "Hey Personal Branding Photography Pune Team,\n\nYour personal branding photography on Instagram is truly inspiring, capturing unique professional stories!\n\nI noticed you're Instagram-only, which often means manual booking. We've put together a quick demo to show how you can automate and streamline your bookings: https://demo.claraverse.in/personal-branding-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "personal-branding-photography-pune",
    "facebook": "—"
  },
  {
    "id": 569,
    "name": "Matrimonial Photos Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Portrait/Matrimonial",
    "instagram": "@matrimonialphotospune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Matrimonial & biodata photos. Instagram-only.",
    "url": "https://demo.claraverse.in/matrimonial-photos-pune",
    "pitch": "Hey Matrimonial Photos Pune Team,\n\nYour matrimonial and biodata photography on Instagram is truly exceptional, capturing such important moments beautifully!\n\nI noticed you're Instagram-only, which often means handling booking inquiries manually. This custom demo link shows how you can automate and streamline that process: https://demo.claraverse.in/matrimonial-photos-pune\n\nWould love to hear your thoughts on this!",
    "slug": "matrimonial-photos-pune",
    "facebook": "—"
  },
  {
    "id": 570,
    "name": "E-commerce Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/E-commerce",
    "instagram": "@ecommercephotopune",
    "websiteStatus": "No website",
    "phone": "+91 9833074070, +91 8655504111 (WhatsApp)",
    "email": "—",
    "notes": "E-commerce product photography. Instagram-only.",
    "url": "https://demo.claraverse.in/e-commerce-photography-pune",
    "pitch": "Hey E-commerce Photography Pune Team,\n\nYour e-commerce product photography on Instagram is truly impressive, showcasing products with such clarity and appeal!\n\nI noticed you're Instagram-only, which often means manual booking inquiries. This custom demo link shows how you could automate and streamline your booking process: https://demo.claraverse.in/e-commerce-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "e-commerce-photography-pune",
    "facebook": "—"
  },
  {
    "id": 571,
    "name": "Amazon Product Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/E-commerce",
    "instagram": "@amazonproductpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Amazon product photography. Instagram-only.",
    "url": "https://demo.claraverse.in/amazon-product-photography-pune",
    "pitch": "Hey Amazon Product Photography Pune Team,\n\nYour Amazon product photography on Instagram is incredibly sharp and professional, making products truly pop!\n\nI noticed you're Instagram-only, which often means handling bookings manually. I've put together a quick demo here to show how you could automate and streamline that process: https://demo.claraverse.in/amazon-product-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "amazon-product-photography-pune",
    "facebook": "—"
  },
  {
    "id": 572,
    "name": "Food Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Food",
    "instagram": "@foodphotographypune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Food photography. Instagram-only.",
    "url": "https://demo.claraverse.in/food-photography-pune",
    "pitch": "Hey Food Photography Pune Team,\n\nYour food photography on Instagram is absolutely mouth-watering and truly captures the essence of each dish!\n\nI noticed you're currently managing all your bookings manually through Instagram DMs or calls, which can be time-consuming. This custom demo link shows how you could automate and streamline that process: https://demo.claraverse.in/food-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "food-photography-pune",
    "facebook": "—"
  },
  {
    "id": 573,
    "name": "Lifestyle Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Lifestyle",
    "instagram": "@lifestylephotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Lifestyle product photography. Instagram-only.",
    "url": "https://demo.claraverse.in/lifestyle-photography-pune",
    "pitch": "Hey Lifestyle Photography Pune Team,\n\nYour lifestyle product photography on Instagram is absolutely stunning – you have a real knack for making products look aspirational!\n\nI noticed you're Instagram-only and likely handling bookings manually, which can be time-consuming. I put together a quick demo here: https://demo.claraverse.in/lifestyle-photography-pune to show how you could automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "lifestyle-photography-pune",
    "facebook": "—"
  },
  {
    "id": 574,
    "name": "Catalog Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Catalog",
    "instagram": "@catalogphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Catalog & lookbook photography. Instagram-only.",
    "url": "https://demo.claraverse.in/catalog-photography-pune",
    "pitch": "Hey Catalog Photography Pune Team,\n\nYour catalog and lookbook photography on Instagram is truly impressive, capturing products with such clarity and style!\n\nGiven you're Instagram-only with no website, managing bookings can be a manual process. I've put together a quick demo at https://demo.claraverse.in/catalog-photography-pune to show how you could automate and streamline this.\n\nWould love to hear your thoughts on this!",
    "slug": "catalog-photography-pune",
    "facebook": "—"
  },
  {
    "id": 575,
    "name": "Corporate Event Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@corporateeventpune",
    "websiteStatus": "No website",
    "phone": "+91-82080-31265",
    "email": "—",
    "notes": "Corporate event photography. Instagram-only.",
    "url": "https://demo.claraverse.in/corporate-event-photography-pune",
    "pitch": "Hey Corporate Event Photography Pune Team,\n\nI was really impressed by your dynamic corporate event photography on Instagram!\n\nIt looks like you're currently managing bookings manually or through DMs without a dedicated website. I've put together a quick demo of how you could automate and streamline your booking process here: https://demo.claraverse.in/corporate-event-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "corporate-event-photography-pune",
    "facebook": "—"
  },
  {
    "id": 576,
    "name": "Conference Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@conferencephotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Conference & seminar photography. Instagram-only.",
    "url": "https://demo.claraverse.in/conference-photography-pune",
    "pitch": "Hey Team,\n\nLove your dynamic conference photography on Instagram!\n\nMissing a dedicated portfolio? Check your custom demo: https://demo.claraverse.in/conference-photography-pune\n\nWould love your feedback!",
    "slug": "conference-photography-pune",
    "facebook": "—"
  },
  {
    "id": 577,
    "name": "AGM Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@agmphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "AGM & corporate photography. Instagram-only.",
    "url": "https://demo.claraverse.in/agm-photography-pune",
    "pitch": "Hey Team,\n\nLove your engaging corporate & event photography on Instagram!\n\nSee how a dedicated platform streamlines bookings: https://demo.claraverse.in/agm-photography-pune\n\nWould love your feedback!",
    "slug": "agm-photography-pune",
    "facebook": "—"
  },
  {
    "id": 578,
    "name": "Product Launch Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@productlaunchpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Product launch photography. Instagram-only.",
    "url": "https://demo.claraverse.in/product-launch-photography-pune",
    "pitch": "Hey Product Launch Photography Pune Team,\n\nLove how you capture the excitement and detail of product launches on Instagram!\n\nSince you're Instagram-only, this often means managing bookings manually, which can be time-consuming. I've put together a quick demo here to show how you could automate and streamline this process: https://demo.claraverse.in/product-launch-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "product-launch-photography-pune",
    "facebook": "—"
  },
  {
    "id": 579,
    "name": "Team Building Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Corporate/Event",
    "instagram": "@teambuildingpune",
    "websiteStatus": "No website",
    "phone": "+91-81043-29191",
    "email": "—",
    "notes": "Team building & corporate photography. Instagram-only.",
    "url": "https://demo.claraverse.in/team-building-photography-pune",
    "pitch": "Hey Team,\n\nYour corporate event and team-building photography on Instagram truly captures the energy and spirit of collaboration!\n\nI noticed you're rocking it on Instagram, but without a website, managing bookings might be a manual process. I've put together a quick demo to show how you could automate and streamline that: https://demo.claraverse.in/team-building-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "team-building-photography-pune",
    "facebook": "—"
  },
  {
    "id": 580,
    "name": "Model Portfolio Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Portfolio",
    "instagram": "@modelportfoliopune",
    "websiteStatus": "No website",
    "phone": "+91-91689-81777",
    "email": "—",
    "notes": "Model portfolio photography. Instagram-only.",
    "url": "https://demo.claraverse.in/model-portfolio-photography-pune",
    "pitch": "Hey Model Portfolio Photography Pune Team,\n\nYour model portfolio work on Instagram is absolutely stunning – the way you capture fashion and personality is truly impressive!\n\nI noticed you're Instagram-only, which often means handling bookings manually. This custom demo link shows how you could automate and streamline your entire booking process: https://demo.claraverse.in/model-portfolio-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "model-portfolio-photography-pune",
    "facebook": "—"
  },
  {
    "id": 581,
    "name": "Portfolio Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Portfolio",
    "instagram": "@portfoliophotopune",
    "websiteStatus": "No website",
    "phone": "+91-70453-60660",
    "email": "—",
    "notes": "Portfolio photography. Instagram-only.",
    "url": "https://demo.claraverse.in/portfolio-photography-pune",
    "pitch": "Hey Portfolio Photography Pune Team,\n\nYour fashion and portfolio photography on Instagram is truly captivating!\n\nI noticed you're currently managing bookings through Instagram, which can be quite time-consuming without a dedicated platform. I've put together a quick demo for you here: https://demo.claraverse.in/portfolio-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "portfolio-photography-pune",
    "facebook": "—"
  },
  {
    "id": 582,
    "name": "Beauty Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Beauty",
    "instagram": "@beautyphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Beauty & cosmetics photography. Instagram-only.",
    "url": "https://demo.claraverse.in/beauty-photography-pune",
    "pitch": "Hey Beauty Photography Pune Team,\n\nYour stunning beauty and cosmetics photography on Instagram is truly captivating!\n\nGiven you're Instagram-only with no website, managing bookings manually must be a huge task. We've tailored a demo at https://demo.claraverse.in/beauty-photography-pune to show how you can automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "beauty-photography-pune",
    "facebook": "—"
  },
  {
    "id": 583,
    "name": "Editorial Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Editorial",
    "instagram": "@editorialphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Editorial photography. Instagram-only.",
    "url": "https://demo.claraverse.in/editorial-photography-pune",
    "pitch": "Hey Editorial Photography Pune Team,\n\nYour high-impact editorial photography on Instagram is absolutely stunning!\n\nNoticed you're Instagram-only, which often means manual bookings. This custom demo link (https://demo.claraverse.in/editorial-photography-pune) could automate and streamline your client bookings.\n\nWould love to hear your thoughts on this!",
    "slug": "editorial-photography-pune",
    "facebook": "—"
  },
  {
    "id": 584,
    "name": "Lookbook Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Fashion/Lookbook",
    "instagram": "@lookbookphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Lookbook photography. Instagram-only.",
    "url": "https://demo.claraverse.in/lookbook-photography-pune",
    "pitch": "Hey Lookbook Photography Team,\n\nYour lookbook photography on Instagram is absolutely stunning, capturing fashion with such an artistic eye!\n\nI noticed you're currently managing bookings without a dedicated website, which can be quite time-consuming. I've put together a quick demo at https://demo.claraverse.in/lookbook-photography-pune to show how you could automate and streamline your entire booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "lookbook-photography-pune",
    "facebook": "—"
  },
  {
    "id": 585,
    "name": "Interior Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Interior",
    "instagram": "@interiorphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Interior photography. Instagram-only.",
    "url": "https://demo.claraverse.in/interior-photography-pune",
    "pitch": "Hey Interior Photography Pune Team,\n\nYour interior photography on Instagram is absolutely stunning, capturing spaces with such an eye for detail and light!\n\nI noticed you're currently Instagram-only, which often means handling bookings manually. This custom demo link shows how you can automate and streamline your booking process: https://demo.claraverse.in/interior-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "interior-photography-pune",
    "facebook": "—"
  },
  {
    "id": 586,
    "name": "Hotel Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Hotel",
    "instagram": "@hotelphotopune",
    "websiteStatus": "No website",
    "phone": "+91 95183 56811, +91 70301 81401, +91 98900 35081",
    "email": "—",
    "notes": "Hotel & resort photography. Instagram-only.",
    "url": "https://demo.claraverse.in/hotel-photography-pune",
    "pitch": "Hey Hotel Photography Pune Team,\n\nYour stunning hotel & resort photography on Instagram is truly captivating!\n\nI noticed you're currently managing bookings without a dedicated website. This custom demo shows how you can automate and streamline your bookings: https://demo.claraverse.in/hotel-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "hotel-photography-pune",
    "facebook": "—"
  },
  {
    "id": 587,
    "name": "Restaurant Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Food",
    "instagram": "@restaurantphotopune",
    "websiteStatus": "No website",
    "phone": "+91-95183-56811",
    "email": "—",
    "notes": "Restaurant & cafe photography. Instagram-only.",
    "url": "https://demo.claraverse.in/restaurant-photography-pune",
    "pitch": "Hey Restaurant Photography Pune Team,\n\nYour restaurant and cafe photography on Instagram is absolutely stunning, capturing the essence of each dish and ambiance so perfectly!\n\nGiven you're Instagram-only, I imagine you're handling all inquiries and bookings manually. I've put together a quick demo at https://demo.claraverse.in/restaurant-photography-pune to show how you could automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "restaurant-photography-pune",
    "facebook": "—"
  },
  {
    "id": 588,
    "name": "3D Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/3D",
    "instagram": "@3dphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "3D architectural photography. Instagram-only.",
    "url": "https://demo.claraverse.in/3d-photography-pune",
    "pitch": "Hey 3D Photography Pune Team,\n\nYour 3D architectural photography on Instagram is truly captivating, showcasing spaces with incredible depth and detail!\n\nNoticed you're Instagram-only, which often means handling bookings manually. Imagine automating that process and letting clients book 24/7! We've put together a quick demo for you here: https://demo.claraverse.in/3d-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "3d-photography-pune",
    "facebook": "—"
  },
  {
    "id": 589,
    "name": "Aerial Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Architecture/Aerial",
    "instagram": "@aerialphotopune",
    "websiteStatus": "No website",
    "phone": "+91 93710 44204 (mobile/WhatsApp), +91 99224 68407 (WhatsApp)",
    "email": "—",
    "notes": "Aerial & drone photography. Instagram-only.",
    "url": "https://demo.claraverse.in/aerial-photography-pune",
    "pitch": "Hey Team,\n\nLove your stunning aerial photography on Instagram!\n\nInstagram's great, but a dedicated site boosts bookings. See your demo:\nhttps://demo.claraverse.in/aerial-photography-pune\n\nWould love your feedback!",
    "slug": "aerial-photography-pune",
    "facebook": "—"
  },
  {
    "id": 590,
    "name": "Wedding Films Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Cinematography",
    "instagram": "@weddingfilmspune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Wedding cinematography. Instagram-only.",
    "url": "https://demo.claraverse.in/wedding-films-pune",
    "pitch": "Hey Team,\n\nYour captivating wedding cinematography on Instagram is truly impressive!\n\nNo dedicated website? We built a demo to showcase your amazing work: https://demo.claraverse.in/wedding-films-pune\n\nWould love your feedback!",
    "slug": "wedding-films-pune",
    "facebook": "—"
  },
  {
    "id": 591,
    "name": "Cinematic Wedding Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Cinematography",
    "instagram": "@cinematicweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Cinematic wedding films. Instagram-only.",
    "url": "https://demo.claraverse.in/cinematic-wedding-pune",
    "pitch": "Hey Cinematic Wedding Pune Team,\n\nYour cinematic wedding films on Instagram are absolutely breathtaking – truly capturing the magic of each couple's special day!\n\nI noticed you're Instagram-only, which often means handling bookings manually. This custom demo link shows how you could automate and streamline your booking process: https://demo.claraverse.in/cinematic-wedding-pune\n\nWould love to hear your thoughts on this!",
    "slug": "cinematic-wedding-pune",
    "facebook": "—"
  },
  {
    "id": 592,
    "name": "Destination Wedding Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Destination",
    "instagram": "@destinationweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Destination wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/destination-wedding-pune",
    "pitch": "Hey Destination Wedding Pune Team,\n\nYour breathtaking destination wedding photography on Instagram truly captures the magic of each moment!\n\nIt looks like you're currently managing all your bookings manually, especially without a dedicated website. I've put together a quick demo of how you could automate and streamline this process, tailored just for you: https://demo.claraverse.in/destination-wedding-pune\n\nWould love to hear your thoughts on this!",
    "slug": "destination-wedding-pune",
    "facebook": "—"
  },
  {
    "id": 593,
    "name": "Maharashtrian Wedding Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Traditional",
    "instagram": "@maharashtrianweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Traditional Maharashtrian wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/maharashtrian-wedding-pune",
    "pitch": "Hey Maharashtrian Wedding Pune Team,\n\nAbsolutely love how your Instagram captures the essence and joy of traditional Maharashtrian weddings!\n\nI noticed you're Instagram-only, which often means handling bookings manually. This custom demo link shows how you could automate and streamline that process: https://demo.claraverse.in/maharashtrian-wedding-pune\n\nWould love to hear your thoughts on this!",
    "slug": "maharashtrian-wedding-pune",
    "facebook": "—"
  },
  {
    "id": 594,
    "name": "Marathi Wedding Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Wedding/Traditional",
    "instagram": "@marathiweddingpune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Marathi wedding photography. Instagram-only.",
    "url": "https://demo.claraverse.in/marathi-wedding-pune",
    "pitch": "Hey Marathi Wedding Pune Team,\n\nYour vibrant Marathi wedding photography on Instagram truly captures the essence and joy of each ceremony!\n\nI noticed you're Instagram-only, which often means handling bookings manually. This custom demo link (https://demo.claraverse.in/marathi-wedding-pune) is tailored to automate and streamline your booking process.\n\nWould love to hear your thoughts on this!",
    "slug": "marathi-wedding-pune",
    "facebook": "—"
  },
  {
    "id": 595,
    "name": "Pet Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Pet/Portrait",
    "instagram": "@petphotographypune",
    "websiteStatus": "No website",
    "phone": "+91-87899-99084",
    "email": "—",
    "notes": "Pet photography. Instagram-only.",
    "url": "https://demo.claraverse.in/pet-photography-pune",
    "pitch": "Hey Pet Photography Pune Team,\n\nYour pet portraits on Instagram are absolutely heartwarming and capture so much personality!\n\nNoticed you're rocking Instagram without a website, which often means manual bookings. This custom demo link shows how you can automate and streamline everything: https://demo.claraverse.in/pet-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "pet-photography-pune",
    "facebook": "—"
  },
  {
    "id": 596,
    "name": "Automotive Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Automotive/Product",
    "instagram": "@automotivephotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Automotive photography. Instagram-only.",
    "url": "https://demo.claraverse.in/automotive-photography-pune",
    "pitch": "Hey Automotive Photography Pune Team,\n\nYour automotive photography on Instagram is absolutely stunning, capturing the essence and power of each vehicle perfectly!\n\nI noticed you're rocking it on Instagram without a website, which often means handling bookings manually. We've put together a quick demo to show how you could automate and streamline your booking process: https://demo.claraverse.in/automotive-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "automotive-photography-pune",
    "facebook": "—"
  },
  {
    "id": 597,
    "name": "Jewelry Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Product/Jewelry",
    "instagram": "@jewelryphotopune",
    "websiteStatus": "No website",
    "phone": "—",
    "email": "—",
    "notes": "Jewelry product photography. Instagram-only.",
    "url": "https://demo.claraverse.in/jewelry-photography-pune",
    "pitch": "Hey Jewelry Photography Pune Team,\n\nYour stunning jewelry product photography on Instagram really caught my eye!\n\nIt looks like you're currently managing bookings manually without a dedicated website, which can be quite time-consuming. I put together a quick demo of how you could automate and streamline this process here: https://demo.claraverse.in/jewelry-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "jewelry-photography-pune",
    "facebook": "—"
  },
  {
    "id": 598,
    "name": "Industrial Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Industrial/Commercial",
    "instagram": "@industrialphotopune",
    "websiteStatus": "No website",
    "phone": "+91-95183-56811",
    "email": "—",
    "notes": "Industrial & factory photography. Instagram-only.",
    "url": "https://demo.claraverse.in/industrial-photography-pune",
    "pitch": "Hey Industrial Photography Pune Team,\n\nI found your incredible industrial & factory photography on Instagram and was genuinely impressed by how you capture the raw power and intricate details of the sector!\n\nI noticed you're Instagram-only, which often means manual booking processes. I've put together a quick demo at https://demo.claraverse.in/industrial-photography-pune to show how you could automate and streamline your bookings.\n\nWould love to hear your thoughts on this!",
    "slug": "industrial-photography-pune",
    "facebook": "—"
  },
  {
    "id": 599,
    "name": "Medical Photography Pune",
    "founder": "Team",
    "city": "Pune",
    "category": "Medical/Commercial",
    "instagram": "@medicalphotopune",
    "websiteStatus": "No website",
    "phone": "9921677520, 8087475047",
    "email": "—",
    "notes": "Medical & healthcare photography. Instagram-only.",
    "url": "https://demo.claraverse.in/medical-photography-pune",
    "pitch": "Hey Medical Photography Pune Team,\n\nYour detailed medical and healthcare photography on Instagram truly stands out!\n\nI noticed you're Instagram-only, which often means handling bookings manually. This demo link shows how you could automate and streamline that process, freeing up your time: https://demo.claraverse.in/medical-photography-pune\n\nWould love to hear your thoughts on this!",
    "slug": "medical-photography-pune",
    "facebook": "—"
  }
];

const sheetsData = {
  "Pune Photographers (100 Leads)": punePhotographers100
};
